  - name: Service
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config
      namespace: "{{ NAMESPACE }}"
      template: svc.yml.j2
      state: "{{ 'present' if WITH_MIGRATION_SYSTEMS else 'absent'}}"

  - name: Deployment
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config
      namespace: "{{ NAMESPACE }}"
      template: deployment.yml.j2
      state: "{{ 'present' if WITH_MIGRATION_SYSTEMS else 'absent'}}"

  - name: Ingress
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config
      namespace: "{{ NAMESPACE }}"
      template: ingress.yml.j2
      apply: yes
      state: "{{ 'present' if WITH_MIGRATION_SYSTEMS else 'absent'}}"

