  - name: Schulconnex group provisioning deployment
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config
      namespace: "{{ NAMESPACE }}"
      template: schulconnex-group-provisioning-deployment.yml.j2
      state: "{{ 'present' if WITH_SCHULCONNEX_PROVISIONING else 'absent'}}"
    tags:
      - deployment

  - name: Schulconnex license provisioning deployment
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config
      namespace: "{{ NAMESPACE }}"
      template: schulconnex-license-provisioning-deployment.yml.j2
      state: "{{ 'present' if WITH_SCHULCONNEX_PROVISIONING else 'absent'}}"
    tags:
      - deployment

  - name: Schulconnex provisioning configmap
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config
      namespace: "{{ NAMESPACE }}"
      template: schulconnex-provisioning-configmap.yml.j2
      apply: yes
    tags:
      - configmap

  - name: Schulconnex provisioning Secret by 1Password
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config
      namespace: "{{ NAMESPACE }}"
      template: schulconnex-provisioning-onepassword.yml.j2
    when: ONEPASSWORD_OPERATOR is defined and ONEPASSWORD_OPERATOR|bool
    tags:
      - 1password

  - name: External Secret for schulconnex provisioning
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config
      namespace: "{{ NAMESPACE }}"
      template: schulconnex-provisioning-external-secret.yml.j2
      state: "{{ 'present' if WITH_BRANCH_MONGO_DB_MANAGEMENT is defined and WITH_BRANCH_MONGO_DB_MANAGEMENT|bool else 'absent' }}"
    when:
      - EXTERNAL_SECRETS_OPERATOR is defined and EXTERNAL_SECRETS_OPERATOR|bool
    tags:
      - 1password
