/* tslint:disable */
/* eslint-disable */
/**
 * Schulcloud-Verbund-Software Server API
 * This is v3 of Schulcloud-Verbund-Software Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LessonMetadataResponse } from './lesson-metadata-response';

/**
 * 
 * @export
 * @interface LessonMetadataListResponse
 */
export interface LessonMetadataListResponse {
    /**
     * The items for the current page.
     * @type {Array<LessonMetadataResponse>}
     * @memberof LessonMetadataListResponse
     */
    'data': Array<LessonMetadataResponse>;
    /**
     * The total amount of items.
     * @type {number}
     * @memberof LessonMetadataListResponse
     */
    'total': number;
    /**
     * The amount of items skipped from the start.
     * @type {number}
     * @memberof LessonMetadataListResponse
     */
    'skip': number;
    /**
     * The page size of the response.
     * @type {number}
     * @memberof LessonMetadataListResponse
     */
    'limit': number;
}

