/* tslint:disable */
/* eslint-disable */
/**
 * Schulcloud-Verbund-Software Server API
 * This is v3 of Schulcloud-Verbund-Software Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LessonLinkedTaskResponse
 */
export interface LessonLinkedTaskResponse {
    /**
     * 
     * @type {string}
     * @memberof LessonLinkedTaskResponse
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof LessonLinkedTaskResponse
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof LessonLinkedTaskResponse
     */
    'descriptionInputFormat': LessonLinkedTaskResponseDescriptionInputFormatEnum;
    /**
     * 
     * @type {string}
     * @memberof LessonLinkedTaskResponse
     */
    'availableDate': string | null;
    /**
     * 
     * @type {string}
     * @memberof LessonLinkedTaskResponse
     */
    'dueDate': string | null;
    /**
     * 
     * @type {boolean}
     * @memberof LessonLinkedTaskResponse
     */
    'private': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof LessonLinkedTaskResponse
     */
    'publicSubmissions': boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof LessonLinkedTaskResponse
     */
    'teamSubmissions': boolean | null;
    /**
     * 
     * @type {string}
     * @memberof LessonLinkedTaskResponse
     */
    'creator': string | null;
    /**
     * 
     * @type {string}
     * @memberof LessonLinkedTaskResponse
     */
    'courseId': string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof LessonLinkedTaskResponse
     */
    'submissionIds': Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof LessonLinkedTaskResponse
     */
    'finishedIds': Array<string>;
}

export const LessonLinkedTaskResponseDescriptionInputFormatEnum = {
    PlainText: 'plainText',
    RichTextCk5Simple: 'richTextCk5Simple',
    RichTextCk4: 'richTextCk4',
    RichTextCk5: 'richTextCk5'
} as const;

export type LessonLinkedTaskResponseDescriptionInputFormatEnum = typeof LessonLinkedTaskResponseDescriptionInputFormatEnum[keyof typeof LessonLinkedTaskResponseDescriptionInputFormatEnum];


