export interface LearnroomConfig {
	FEATURE_COMMON_CARTRIDGE_COURSE_EXPORT_ENABLED: boolean;
	GEOGEBRA_BASE_URL: string;
	FEATURE_COLUMN_BOARD_ENABLED: boolean;
	FEATURE_COPY_SERVICE_ENABLED: boolean;
	FEATURE_COMMON_CARTRIDGE_COURSE_IMPORT_ENABLED: boolean;
	FEATURE_COMMON_CARTRIDGE_COURSE_IMPORT_MAX_FILE_SIZE: number;
}
