info:
  title: Schul-Cloud Legacy API
  description:
    This is the API specification for the Schul-Cloud legacy API.
    
  contact:
    name: support
    email: info@hpi-schul-cloud.de
  license:
    name: GPL-3.0
    url: 'https://github.com/hpi-schul-cloud/schulcloud-server/blob/master/LICENSE'
  version: 1.0.0
servers:
  - url: /legacy/v1/

paths:
  /me:
    $ref: '../me/docs/openapi.yaml#/paths/~1me'
  /version:
    $ref: '../versionService/openapi.yaml#/paths/~1version'

openapi: 3.0.2