export interface ManagementSeedDataConfig {
	SC_THEME: string;
	SC_SHORTNAME: string;
	SCHULCONNEX_CLIENT_ID?: string;
	SCHULCONNEX_CLIENT_SECRET?: string;

	MEDIA_SOURCE_VIDIS_USERNAME?: string;
	MEDIA_SOURCE_VIDIS_PASSWORD?: string;
	MEDIA_SOURCE_BILO_CLIENT_ID?: string;
	MEDIA_SOURCE_BILO_CLIENT_SECRET?: string;

	NEXTCLOUD_SOCIALLOGIN_OIDC_INTERNAL_NAME?: string;
	NEXTCLOUD_BASE_URL?: string;
	NEXTCLOUD_CLIENT_ID?: string;
	NEXTCLOUD_CLIENT_SECRET?: string;
	NEXTCLOUD_SCOPES?: string;
	CTL_SEED_SECRET_ONLINE_DIA_MATHE?: string;
	CTL_SEED_SECRET_ONLINE_DIA_DEUTSCH?: string;
	CTL_SEED_SECRET_MERLIN?: string;
}
