/* tslint:disable */
/* eslint-disable */
/**
 * HPI Schul-Cloud Server API
 * This is v3 of HPI Schul-Cloud Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export * from './clients/courses-api';
export * from './clients/dashboard-api';
export * from './clients/default-api';
export * from './clients/news-api';
export * from './clients/rooms-api';
export * from './clients/task-api';
export * from './clients/user-api';

