export enum AuthorizableReferenceType {
	'User' = 'users',
	'School' = 'schools',
	'Course' = 'courses',
	'CourseGroup' = 'coursegroups',
	'Task' = 'tasks',
	'Lesson' = 'lessons',
	'Team' = 'teams',
	'Submission' = 'submissions',
	'SchoolExternalToolEntity' = 'school-external-tools',
	'BoardNode' = 'boardnodes',
	'ContextExternalToolEntity' = 'context-external-tools',
	'ExternalTool' = 'external-tools',
	'Instance' = 'instances',
}
