version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "01:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 99
  versioning-strategy: increase-if-necessary
  rebase-strategy: disabled
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "01:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 99
  rebase-strategy: disabled
