pull_request_rules:
  - name: auto merge when label is set
    conditions:
      - label!=WIP
      - label!=waiting
      - label=ready to merge
      - status-success~=Travis CI
      - status-success~=Codacy
      - status-success~=pullapprove
    actions:
      merge:
        method: merge
        strict: true
  - name: remove ready to merge label when merged
    conditions:
      - merged
      - label=ready to merge
    actions:
      label:
        add:
          - auto_merged
        remove:
          - ready to merge
  - name: remove "ready to merge" label when pull is not approved
    conditions:
      - status-failure~=pullapprove
      - label~=ready to merge
      - -merged
    actions:
      comment:
        message: The "ready to merge" label can only be set after one pull request approval
      label:
        remove:
          - ready to merge
