version: 3

pullapprove_conditions:
  - condition: "'WIP' not in labels"
    unmet_status: pending
    explanation: 'Work in progress'
  - condition: "'- [ ]' not in body"
    unmet_status: failure
    explanation: 'Please finish all the required checklist tasks'
#- condition: "'Travis*' in statuses.succeeded" # Not working yet
#  unmet_status: failure
#  explanation: "Tests must pass before review starts"
#- condition: "'stickler*' in statuses.succeeded"
#  unmet_status: failure
#  explanation: "Linter must pass before review starts"

notifications:
  - when: pull_request.opened
    comment: |
      Hey @{{ author }}, thanks for the PR! The review will start once
      the tests, CI checks and PR requirements (see checklist in your PR) have passed.
  - when: pullapprove.approved
    comment: The review is completed. @{{ author }}, please follow further instructions from
      our Review-Guidelines https://docs.hpi-schul-cloud.org/display/SCDOK/Review-Guidelines

groups:
  sc-admins:
    reviews:
      required: 1 # 1 approval from this group are required
    reviewers:
      teams:
        - sc-admins
        - CoreDevs
