services:
  rabbitmq:
    image: rabbitmq:3.8.9-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"

  minio:
    image: quay.io/minio/minio
    restart: always
    ports:
      - "9010:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: miniouser
      MINIO_ROOT_PASSWORD: miniouser
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"