/* tslint:disable */
/* eslint-disable */
/**
 * Schulcloud-Verbund-Software Server API
 * This is v3 of Schulcloud-Verbund-Software Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Action } from './action';
// May contain unused imports in some cases
// @ts-ignore
import type { Permission } from './permission';

/**
 *
 * @export
 * @interface AuthorizationContextParams
 */
export interface AuthorizationContextParams {
	/**
	 *
	 * @type {Action}
	 * @memberof AuthorizationContextParams
	 */
	action: Action;
	/**
	 * User permissions that are needed to execute the operation.
	 * @type {Array<Permission>}
	 * @memberof AuthorizationContextParams
	 */
	requiredPermissions: Array<Permission>;
}
