/* tslint:disable */
/* eslint-disable */
/**
 * HPI Schul-Cloud Server API
 * This is v3 of HPI Schul-Cloud Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ContentElementType } from './content-element-type';
// May contain unused imports in some cases
// @ts-ignore
import type { FileElementContent } from './file-element-content';
// May contain unused imports in some cases
// @ts-ignore
import type { FileElementResponse } from './file-element-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RichTextElementResponse } from './rich-text-element-response';
// May contain unused imports in some cases
// @ts-ignore
import type { TimestampsResponse } from './timestamps-response';

/**
 * @type BoardSubmissionControllerCreateElement201Response
 * @export
 */
export type BoardSubmissionControllerCreateElement201Response = FileElementResponse | RichTextElementResponse;


