/* tslint:disable */
/* eslint-disable */
/**
 * HPI Schul-Cloud Server API
 * This is v3 of HPI Schul-Cloud Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ContentElementType } from './content-element-type';
// May contain unused imports in some cases
// @ts-ignore
import type { DrawingContentBody } from './drawing-content-body';

/**
 * 
 * @export
 * @interface DrawingElementContentBody
 */
export interface DrawingElementContentBody {
    /**
     * 
     * @type {ContentElementType}
     * @memberof DrawingElementContentBody
     */
    'type': ContentElementType;
    /**
     * 
     * @type {DrawingContentBody}
     * @memberof DrawingElementContentBody
     */
    'content': DrawingContentBody;
}



