/* tslint:disable */
/* eslint-disable */
/**
 * HPI Schul-Cloud Server API
 * This is v3 of HPI Schul-Cloud Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MeUserResponse
 */
export interface MeUserResponse {
    /**
     * 
     * @type {string}
     * @memberof MeUserResponse
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof MeUserResponse
     */
    'firstName': string;
    /**
     * 
     * @type {string}
     * @memberof MeUserResponse
     */
    'lastName': string;
    /**
     * 
     * @type {string}
     * @memberof MeUserResponse
     */
    'customAvatarBackgroundColor'?: string;
}

