/* tslint:disable */
/* eslint-disable */
/**
 * HPI Schul-Cloud Server API
 * This is v3 of HPI Schul-Cloud Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MediaExternalToolElementContent } from './media-external-tool-element-content';
// May contain unused imports in some cases
// @ts-ignore
import type { TimestampsResponse } from './timestamps-response';

/**
 * 
 * @export
 * @interface MediaExternalToolElementResponse
 */
export interface MediaExternalToolElementResponse {
    /**
     * The id of the media external tool element
     * @type {string}
     * @memberof MediaExternalToolElementResponse
     */
    'id': string;
    /**
     * The content of the media external tool element
     * @type {MediaExternalToolElementContent}
     * @memberof MediaExternalToolElementResponse
     */
    'content': MediaExternalToolElementContent;
    /**
     * The timestamps of the media external tool element
     * @type {TimestampsResponse}
     * @memberof MediaExternalToolElementResponse
     */
    'timestamps': TimestampsResponse;
}

