/* tslint:disable */
/* eslint-disable */
/**
 * HPI Schul-Cloud Server API
 * This is v3 of HPI Schul-Cloud Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MessageOrigin } from './message-origin';

/**
 * 
 * @export
 * @interface Message
 */
export interface Message {
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    'text': string;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    'timestamp': string;
    /**
     * 
     * @type {MessageOrigin}
     * @memberof Message
     */
    'origin': MessageOrigin;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    'url': string;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    'status': string;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    'createdAt': string;
}

