/* tslint:disable */
/* eslint-disable */
/**
 * HPI Schul-Cloud Server API
 * This is v3 of HPI Schul-Cloud Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Oauth2MigrationParams
 */
export interface Oauth2MigrationParams {
    /**
     * 
     * @type {string}
     * @memberof Oauth2MigrationParams
     */
    'redirectUri': string;
    /**
     * 
     * @type {string}
     * @memberof Oauth2MigrationParams
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof Oauth2MigrationParams
     */
    'systemId': string;
}

