/* tslint:disable */
/* eslint-disable */
/**
 * HPI Schul-Cloud Server API
 * This is v3 of HPI Schul-Cloud Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OauthClientResponse
 */
export interface OauthClientResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof OauthClientResponse
     */
    'allowed_cors_origins'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof OauthClientResponse
     */
    'audience': Array<string>;
    /**
     * 
     * @type {string}
     * @memberof OauthClientResponse
     */
    'authorization_code_grant_access_token_lifespan': string;
    /**
     * 
     * @type {string}
     * @memberof OauthClientResponse
     */
    'authorization_code_grant_id_token_lifespan': string;
    /**
     * 
     * @type {string}
     * @memberof OauthClientResponse
     */
    'authorization_code_grant_refresh_token_lifespan': string;
    /**
     * Boolean value specifying whether the RP requires that a sid (session ID) Claim.
     * @type {boolean}
     * @memberof OauthClientResponse
     */
    'backchannel_logout_session_required': boolean;
    /**
     * RP URL that will cause the RP to log itself out when sent a Logout Token by the OP.
     * @type {string}
     * @memberof OauthClientResponse
     */
    'backchannel_logout_uri': string;
    /**
     * 
     * @type {string}
     * @memberof OauthClientResponse
     */
    'client_credentials_grant_access_token_lifespan': string;
    /**
     * Id of the client.
     * @type {string}
     * @memberof OauthClientResponse
     */
    'client_id': string;
    /**
     * Human-readable string name of the client presented to the end-user.
     * @type {string}
     * @memberof OauthClientResponse
     */
    'client_name': string;
    /**
     * SecretExpiresAt is an integer holding the time at which the client secret will expire or 0 if it will not expire.
     * @type {number}
     * @memberof OauthClientResponse
     */
    'client_secret_expires_at': number;
    /**
     * ClientUri is an URL string of a web page providing information about the client.
     * @type {string}
     * @memberof OauthClientResponse
     */
    'client_uri': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof OauthClientResponse
     */
    'contacts'?: Array<string>;
    /**
     * CreatedAt returns the timestamp of the clients creation.
     * @type {string}
     * @memberof OauthClientResponse
     */
    'created_at': string;
    /**
     * Boolean value specifying whether the RP requires that iss (issuer) and sid (session ID) query parameters.
     * @type {boolean}
     * @memberof OauthClientResponse
     */
    'frontchannel_logout_session_required': boolean;
    /**
     * RP URL that will cause the RP to log itself out when rendered in an iframe by the OP.
     * @type {string}
     * @memberof OauthClientResponse
     */
    'frontchannel_logout_uri': string;
    /**
     * The grant types of the Oauth2 client.
     * @type {Array<string>}
     * @memberof OauthClientResponse
     */
    'grant_types'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof OauthClientResponse
     */
    'implicit_grant_access_token_lifespan': string;
    /**
     * 
     * @type {string}
     * @memberof OauthClientResponse
     */
    'implicit_grant_id_token_lifespan': string;
    /**
     * 
     * @type {object}
     * @memberof OauthClientResponse
     */
    'jwks': object;
    /**
     * URL for the clients JSON Web Key Set [JWK] document
     * @type {string}
     * @memberof OauthClientResponse
     */
    'jwks_uri': string;
    /**
     * 
     * @type {string}
     * @memberof OauthClientResponse
     */
    'jwt_bearer_grant_access_token_lifespan': string;
    /**
     * LogoUri is an URL string that references a logo for the client.
     * @type {string}
     * @memberof OauthClientResponse
     */
    'logo_uri': string;
    /**
     * 
     * @type {object}
     * @memberof OauthClientResponse
     */
    'metadata': object;
    /**
     * Owner is a string identifying the owner of the OAuth 2.0 Client.
     * @type {string}
     * @memberof OauthClientResponse
     */
    'owner': string;
    /**
     * 
     * @type {string}
     * @memberof OauthClientResponse
     */
    'password_grant_access_token_lifespan': string;
    /**
     * 
     * @type {string}
     * @memberof OauthClientResponse
     */
    'password_grant_refresh_token_lifespan': string;
    /**
     * PolicyUri is a URL string that points to a human-readable privacy policy document
     * @type {string}
     * @memberof OauthClientResponse
     */
    'policy_uri': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof OauthClientResponse
     */
    'post_logout_redirect_uris'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof OauthClientResponse
     */
    'redirect_uris'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof OauthClientResponse
     */
    'refresh_token_grant_access_token_lifespan': string;
    /**
     * 
     * @type {string}
     * @memberof OauthClientResponse
     */
    'refresh_token_grant_id_token_lifespan': string;
    /**
     * 
     * @type {string}
     * @memberof OauthClientResponse
     */
    'refresh_token_grant_refresh_token_lifespan': string;
    /**
     * RegistrationAccessToken can be used to update, get, or delete the OAuth2 Client.
     * @type {string}
     * @memberof OauthClientResponse
     */
    'registration_access_token': string;
    /**
     * RegistrationClientURI is the URL used to update, get, or delete the OAuth2 Client.
     * @type {string}
     * @memberof OauthClientResponse
     */
    'registration_client_uri': string;
    /**
     * JWS [JWS] alg algorithm [JWA] that MUST be used for signing Request Objects sent to the OP.
     * @type {string}
     * @memberof OauthClientResponse
     */
    'request_object_signing_alg': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof OauthClientResponse
     */
    'request_uris'?: Array<string>;
    /**
     * The response types of the Oauth2 client.
     * @type {Array<string>}
     * @memberof OauthClientResponse
     */
    'response_types'?: Array<string>;
    /**
     * Scope is a string containing a space-separated list of scope values (as described in Section 3.3 of OAuth 2.0 [RFC6749]) that the client can use when requesting access tokens.
     * @type {string}
     * @memberof OauthClientResponse
     */
    'scope': string;
    /**
     * URL using the https scheme to be used in calculating Pseudonymous Identifiers by the OP.
     * @type {string}
     * @memberof OauthClientResponse
     */
    'sector_identifier_uri': string;
    /**
     * SubjectType requested for responses to this Client. The subject_types_supported Discovery parameter contains a list of the supported subject_type values for this server. Valid types include pairwise and public.
     * @type {string}
     * @memberof OauthClientResponse
     */
    'subject_type': string;
    /**
     * 
     * @type {string}
     * @memberof OauthClientResponse
     */
    'token_endpoint_auth_method': string;
    /**
     * 
     * @type {string}
     * @memberof OauthClientResponse
     */
    'token_endpoint_auth_signing_alg': string;
    /**
     * TermsOfServiceUri is a URL string that points to a human-readable terms of service document for the client.
     * @type {string}
     * @memberof OauthClientResponse
     */
    'tos_uri': string;
    /**
     * UpdatedAt returns the timestamp of the last update.
     * @type {string}
     * @memberof OauthClientResponse
     */
    'updated_at': string;
    /**
     * JWS alg algorithm [JWA] REQUIRED for signing UserInfo Responses. 
     * @type {string}
     * @memberof OauthClientResponse
     */
    'userinfo_signed_response_alg': string;
}

