/* tslint:disable */
/* eslint-disable */
/**
 * HPI Schul-Cloud Server API
 * This is v3 of HPI Schul-Cloud Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RichText
 */
export interface RichText {
    /**
     * Content of the rich text element
     * @type {string}
     * @memberof RichText
     */
    'content': string;
    /**
     * Input format of the rich text element
     * @type {string}
     * @memberof RichText
     */
    'type': RichTextType;
}

export const RichTextType = {
    PLAIN_TEXT: 'plainText',
    RICH_TEXT_CK5_SIMPLE: 'richTextCk5Simple',
    RICH_TEXT_CK4: 'richTextCk4',
    RICH_TEXT_CK5: 'richTextCk5'
} as const;

export type RichTextType = typeof RichTextType[keyof typeof RichTextType];


