/* tslint:disable */
/* eslint-disable */
/**
 * HPI Schul-Cloud Server API
 * This is v3 of HPI Schul-Cloud Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const RoleName = {
    ADMINISTRATOR: 'administrator',
    COURSE_ADMINISTRATOR: 'courseAdministrator',
    COURSE_STUDENT: 'courseStudent',
    COURSE_SUBSTITUTION_TEACHER: 'courseSubstitutionTeacher',
    COURSE_TEACHER: 'courseTeacher',
    DEMO: 'demo',
    DEMO_STUDENT: 'demoStudent',
    DEMO_TEACHER: 'demoTeacher',
    EXPERT: 'expert',
    HELPDESK: 'helpdesk',
    STUDENT: 'student',
    SUPERHERO: 'superhero',
    TEACHER: 'teacher',
    TEAMADMINISTRATOR: 'teamadministrator',
    TEAMEXPERT: 'teamexpert',
    TEAMLEADER: 'teamleader',
    TEAMMEMBER: 'teammember',
    TEAMOWNER: 'teamowner',
    USER: 'user'
} as const;

export type RoleName = typeof RoleName[keyof typeof RoleName];



