/* tslint:disable */
/* eslint-disable */
/**
 * HPI Schul-Cloud Server API
 * This is v3 of HPI Schul-Cloud Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TaskCopyApiParams
 */
export interface TaskCopyApiParams {
    /**
     * Destination course parent Id the task is copied to
     * @type {string}
     * @memberof TaskCopyApiParams
     */
    'courseId'?: string;
    /**
     * Destination lesson parent Id the task is copied to
     * @type {string}
     * @memberof TaskCopyApiParams
     */
    'lessonId'?: string;
}

