/* tslint:disable */
/* eslint-disable */
/**
 * HPI Schul-Cloud Server API
 * This is v3 of HPI Schul-Cloud Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ToolReferenceResponse } from './tool-reference-response';

/**
 * 
 * @export
 * @interface ToolReferenceListResponse
 */
export interface ToolReferenceListResponse {
    /**
     * 
     * @type {Array<ToolReferenceResponse>}
     * @memberof ToolReferenceListResponse
     */
    'data': Array<ToolReferenceResponse>;
}

