/* tslint:disable */
/* eslint-disable */
/**
 * HPI Schul-Cloud Server API
 * This is v3 of HPI Schul-Cloud Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ContextExternalToolConfigurationStatusResponse } from './context-external-tool-configuration-status-response';

/**
 * 
 * @export
 * @interface ToolReferenceResponse
 */
export interface ToolReferenceResponse {
    /**
     * The id of the tool in the context
     * @type {string}
     * @memberof ToolReferenceResponse
     */
    'contextToolId': string;
    /**
     * The description of the tool
     * @type {string}
     * @memberof ToolReferenceResponse
     */
    'description'?: string;
    /**
     * The url of the logo which is stored in the db
     * @type {string}
     * @memberof ToolReferenceResponse
     */
    'logoUrl'?: string;
    /**
     * The display name of the tool
     * @type {string}
     * @memberof ToolReferenceResponse
     */
    'displayName': string;
    /**
     * Whether the tool should be opened in a new tab
     * @type {boolean}
     * @memberof ToolReferenceResponse
     */
    'openInNewTab': boolean;
    /**
     * The status of the tool
     * @type {ContextExternalToolConfigurationStatusResponse}
     * @memberof ToolReferenceResponse
     */
    'status': ContextExternalToolConfigurationStatusResponse;
}

