export interface SchulconnexClientConfig {
	SCHULCONNEX_CLIENT__PERSON_INFO_TIMEOUT_IN_MS: number;
	SCHULCONNEX_CLIENT__PERSONEN_INFO_TIMEOUT_IN_MS: number;
	SCHULCONNEX_CLIENT__POLICIES_INFO_TIMEOUT_IN_MS: number;
	SCHULCONNEX_CLIENT__API_URL?: string;
	SCHULCONNEX_CLIENT__TOKEN_ENDPOINT?: string;
	SCHULCONNEX_CLIENT__CLIENT_ID?: string;
	SCHULCONNEX_CLIENT__CLIENT_SECRET?: string;
}
