const base64Files = require('./base64Files');
const fileStorage = require('./fileStorage');
const link = require('./link');
const news = require('./news');
const newsEvents = require('./news/events');
const content = require('./content');
const calendar = require('./calendar');
const school = require('./school');
const system = require('./system');
const lesson = require('./lesson');
const account = require('./account');
const authentication = require('./authentication');
const user = require('./user');
const role = require('./role');
const helpers = require('./helpers');
const resolve = require('./resolve');
const federalState = require('./federalState');
const userGroup = require('./user-group');
const teams = require('./teams');
const teamEvents = require('./teams/events');
const homework = require('./homework');
const passwordRecovery = require('./passwordRecovery');
const releases = require('./releases');
const statistic = require('./statistic');
const statisticMails = require('./statisticMail');
const consent = require('./consent');
const oauth2 = require('./oauth2');
const roster = require('./roster');
const ldap = require('./ldap');
const ldapConfig = require('./ldap-config');
const sync = require('./sync');
const datasources = require('./datasources');
const rocketChat = require('./rocketChat');
const me = require('./me');
const help = require('./help');
const database = require('../utils/database');
const etherpad = require('./etherpad');
const storageProvider = require('./storageProvider');
const activation = require('./activation');
const config = require('./config');
const syncLegacyIndexes = require('./sync-legacy-indexes');
const docs = require('./docs');

module.exports = function initializeServices() {
	const app = this;
	// connect mongoose to the database
	database.connect();

	// register services
	app.configure(docs);
	app.configure(authentication);
	app.configure(base64Files);
	app.configure(user);
	app.configure(role);
	app.configure(account);
	app.configure(system);
	app.configure(school);
	app.configure(resolve);
	app.configure(userGroup);
	app.configure(teams);
	app.configure(content);
	app.configure(calendar);
	app.configure(lesson);
	app.configure(fileStorage);
	app.configure(link);
	app.configure(news);
	app.configure(helpers);
	app.configure(homework);
	app.configure(federalState);
	app.configure(passwordRecovery);
	app.configure(releases);
	app.configure(statistic);
	app.configure(statisticMails);
	app.configure(consent);
	app.configure(ldap);
	app.configure(ldapConfig);
	app.configure(sync);
	app.configure(me);
	app.configure(help);
	app.configure(rocketChat);
	app.configure(oauth2);
	app.configure(roster);
	app.configure(datasources);
	app.configure(etherpad);
	app.configure(storageProvider);
	app.configure(activation);
	app.configure(syncLegacyIndexes);
	app.configure(config);

	// initialize events
	newsEvents.configure(app);
	teamEvents.configure(app);
};
