import { Application as FeathersApplication } from '@feathersjs/feathers';

import base64Files from './base64Files';
import fileStorage from './fileStorage';
import link from './link';
import news from './news';
import newsEvents from './news/events';
import content from './content';
import calendar from './calendar';
import ltiTool from './ltiTool';
import school from './school';
import system from './system';
import lesson from './lesson';
import analytics from './analytics';
import edusharing from './edusharing';
import account from './account';
import authentication from './authentication';
import user from './user';
import role from './role';
import helpers from './helpers';
import resolve from './resolve';
import federalState from './federalState';
import userGroup from './user-group';
import teams from './teams';
import teamEvents from './teams/events';
import homework from './homework';
import passwordRecovery from './passwordRecovery';
import notification from './notification';
import releases from './releases';
import helpdesk from './helpdesk';
import statistic from './statistic';
import statisticMails from './statisticMail';
import wopi from './wopi';
import pseudonym from './pseudonym';
import consent from './consent';
import oauth2 from './oauth2';
import roster from './roster';
import ldap from './ldap';
import ldapConfig from './ldap-config';
import sync from './sync';
import datasources from './datasources';
import rocketChat from './rocketChat';
import webuntis from './webuntis';
import me from './me';
import help from './help';
import database from '../utils/database';
import alert from './alert';
import videoconference from './videoconference';
import messenger from './messenger';
import messengerSync from './messengerSync';
import nexboard from './nexboard';
import etherpad from './etherpad';
import storageProvider from './storageProvider';
import activation from './activation';
import config from './config';
import version from './versionService';
import docs from './docs';

export default (app: FeathersApplication): void => {
	// connect mongoose to the database
	database.connect();

	// register services
	app.configure(docs);
	app.configure(authentication);
	app.configure(analytics);
	app.configure(base64Files);
	app.configure(user);
	app.configure(role);
	app.configure(account);
	app.configure(system);
	app.configure(school);
	app.configure(resolve);
	app.configure(userGroup);
	app.configure(teams);
	app.configure(ltiTool);
	app.configure(content);
	app.configure(calendar);
	app.configure(lesson);
	app.configure(fileStorage);
	app.configure(link);
	app.configure(news);
	app.configure(helpers);
	app.configure(homework);
	app.configure(federalState);
	app.configure(passwordRecovery);
	app.configure(notification);
	app.configure(releases);
	app.configure(helpdesk);
	app.configure(statistic);
	app.configure(statisticMails);
	app.configure(wopi);
	app.configure(pseudonym);
	app.configure(consent);
	app.configure(ldap);
	app.configure(ldapConfig);
	app.configure(sync);
	app.configure(me);
	app.configure(help);
	app.configure(rocketChat);
	app.configure(oauth2);
	app.configure(roster);
	app.configure(datasources);
	app.configure(alert);
	app.configure(edusharing);
	app.configure(webuntis);
	app.configure(videoconference);
	app.configure(messenger);
	app.configure(messengerSync);
	app.configure(nexboard);
	app.configure(etherpad);
	app.configure(storageProvider);
	app.configure(activation);
	app.configure(config);
	app.configure(version);

	// initialize events
	newsEvents.configure(app);
	teamEvents.configure(app);
};
