/* tslint:disable */
/* eslint-disable */
/**
 * 
 * TIP-Rest Api v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DobjTeilnehmer } from './dobj-teilnehmer';

/**
 * 
 * @export
 * @interface DobjExamen
 */
export interface DobjExamen {
    /**
     * 
     * @type {string}
     * @memberof DobjExamen
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof DobjExamen
     */
    'version'?: string;
    /**
     * 
     * @type {string}
     * @memberof DobjExamen
     */
    'examenUID'?: string;
    /**
     * 
     * @type {string}
     * @memberof DobjExamen
     */
    'schuleId'?: string;
    /**
     * 
     * @type {string}
     * @memberof DobjExamen
     */
    'schuleName'?: string;
    /**
     * 
     * @type {string}
     * @memberof DobjExamen
     */
    'schuleNummer'?: string;
    /**
     * 
     * @type {string}
     * @memberof DobjExamen
     */
    'kursName'?: string;
    /**
     * 
     * @type {string}
     * @memberof DobjExamen
     */
    'kursId'?: string;
    /**
     * 
     * @type {string}
     * @memberof DobjExamen
     */
    'ileaPaketCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof DobjExamen
     */
    'ileaPaketFachCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof DobjExamen
     */
    'ileaPaketJahrgangsstufe'?: string;
    /**
     * 
     * @type {string}
     * @memberof DobjExamen
     */
    'dtExamenBeginn'?: string;
    /**
     * 
     * @type {string}
     * @memberof DobjExamen
     */
    'beginnDatum'?: string;
    /**
     * 
     * @type {string}
     * @memberof DobjExamen
     */
    'dtExamenEnde'?: string;
    /**
     * 
     * @type {string}
     * @memberof DobjExamen
     */
    'endeDatum'?: string;
    /**
     * 
     * @type {string}
     * @memberof DobjExamen
     */
    'dtErstelltAm'?: string;
    /**
     * 
     * @type {string}
     * @memberof DobjExamen
     */
    'erstelltDurch'?: string;
    /**
     * 
     * @type {string}
     * @memberof DobjExamen
     */
    'dtGeaendertAm'?: string;
    /**
     * 
     * @type {string}
     * @memberof DobjExamen
     */
    'geandertDurch'?: string;
    /**
     * 
     * @type {Array<DobjTeilnehmer>}
     * @memberof DobjExamen
     */
    'listSchueler'?: Array<DobjTeilnehmer>;
}

