/* tslint:disable */
/* eslint-disable */
/**
 * 
 * TIP-Rest Api v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DobjZugangsdaten
 */
export interface DobjZugangsdaten {
    /**
     * 
     * @type {string}
     * @memberof DobjZugangsdaten
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof DobjZugangsdaten
     */
    'version'?: string;
    /**
     * 
     * @type {string}
     * @memberof DobjZugangsdaten
     */
    'loginId'?: string;
    /**
     * 
     * @type {string}
     * @memberof DobjZugangsdaten
     */
    'kzKennwortAbgelaufen'?: string;
    /**
     * 
     * @type {string}
     * @memberof DobjZugangsdaten
     */
    'kennwortGueltigBis'?: string;
    /**
     * 
     * @type {string}
     * @memberof DobjZugangsdaten
     */
    'zugangGueltigAb'?: string;
    /**
     * 
     * @type {string}
     * @memberof DobjZugangsdaten
     */
    'zugangGueltigBis'?: string;
}

