/* tslint:disable */
/* eslint-disable */
/**
 * 
 * TIP-Rest Api v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DobjAuswahl
 */
export interface DobjAuswahl {
    /**
     * 
     * @type {string}
     * @memberof DobjAuswahl
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof DobjAuswahl
     */
    'version'?: string;
    /**
     * 
     * @type {string}
     * @memberof DobjAuswahl
     */
    'fieldLabel'?: string;
    /**
     * 
     * @type {string}
     * @memberof DobjAuswahl
     */
    'selectLabel'?: string;
}

