/* tslint:disable */
/* eslint-disable */
/**
 * 
 * TIP-Rest Api v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DobjSchueler
 */
export interface DobjSchueler {
    /**
     * 
     * @type {string}
     * @memberof DobjSchueler
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof DobjSchueler
     */
    'version'?: string;
    /**
     * 
     * @type {string}
     * @memberof DobjSchueler
     */
    'schuleId'?: string;
    /**
     * 
     * @type {string}
     * @memberof DobjSchueler
     */
    'klasseId'?: string;
    /**
     * 
     * @type {string}
     * @memberof DobjSchueler
     */
    'kursId'?: string;
    /**
     * 
     * @type {string}
     * @memberof DobjSchueler
     */
    'nachname'?: string;
    /**
     * 
     * @type {string}
     * @memberof DobjSchueler
     */
    'vorname'?: string;
    /**
     * 
     * @type {string}
     * @memberof DobjSchueler
     */
    'geburtsdatum'?: string;
    /**
     * 
     * @type {string}
     * @memberof DobjSchueler
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof DobjSchueler
     */
    'kzZugang'?: string;
    /**
     * 
     * @type {string}
     * @memberof DobjSchueler
     */
    'geandertDurch'?: string;
}

