/* tslint:disable */
/* eslint-disable */
/**
 * 
 * TIP-Rest Api v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DobjKurslehrerZuordnung
 */
export interface DobjKurslehrerZuordnung {
    /**
     * 
     * @type {string}
     * @memberof DobjKurslehrerZuordnung
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof DobjKurslehrerZuordnung
     */
    'version'?: string;
    /**
     * 
     * @type {string}
     * @memberof DobjKurslehrerZuordnung
     */
    'kursId'?: string;
    /**
     * 
     * @type {string}
     * @memberof DobjKurslehrerZuordnung
     */
    'personalSchuleVerhaeltnisId'?: string;
    /**
     * 
     * @type {string}
     * @memberof DobjKurslehrerZuordnung
     */
    'lehrerName'?: string;
    /**
     * 
     * @type {string}
     * @memberof DobjKurslehrerZuordnung
     */
    'erstelltVon'?: string;
}

