/* tslint:disable */
/* eslint-disable */
/**
 * 
 * TIP-Rest Api v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Fehler
 */
export interface Fehler {
    /**
     * Welchen Aspekt / welchen Bereich / welche Unterliste ist betroffen?
     * @type {string}
     * @memberof Fehler
     */
    'reference'?: string;
    /**
     * Feldname, falls ein konkretes (Eingabe)feld betroffen/ursächlich ist.
     * @type {string}
     * @memberof Fehler
     */
    'fieldName'?: string;
    /**
     * Der, dem Nutzer anzuzeigende Fehlertext.
     * @type {string}
     * @memberof Fehler
     */
    'errorText'?: string;
    /**
     * Technische Zusatzinformationen, StackTrace, Prozedurname, Statement etc. insofern keine sicherheitsrelevanten Informationen preisgegeben würden.
     * @type {string}
     * @memberof Fehler
     */
    'errorSource'?: string;
}

