/* tslint:disable */
/* eslint-disable */
/**
 * 
 * TIP-Rest Api v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Objekt zur Beantwortung von Berechtigungsanfragen
 */
export interface Objekt zur Beantwortung von Berechtigungsanfragen {
    /**
     * Dient in erster Linie zur Verhinderung von Cross-Site-Request-Forgery.
     * @type {string}
     * @memberof Objekt zur Beantwortung von Berechtigungsanfragen
     */
    'authToken'?: string;
    /**
     * Beinhaltet die Liste aller technischen Objekte für die der Anfrager berechtigt ist und welche zu dem angegebenen prefix passen.
     * @type {Array<string>}
     * @memberof Objekt zur Beantwortung von Berechtigungsanfragen
     */
    'listTechObj'?: Array<string>;
    /**
     * Beinhaltet die Liste aller relevanten syeis für den Prefix
     * @type {{ [key: string]: string; }}
     * @memberof Objekt zur Beantwortung von Berechtigungsanfragen
     */
    'listSystemeinstellung'?: { [key: string]: string; };
    /**
     * Beinhaltet die Liste aller relevanten listToolTipKeys für den Prefix
     * @type {Array<string>}
     * @memberof Objekt zur Beantwortung von Berechtigungsanfragen
     */
    'listToolTipKey'?: Array<string>;
}

