/* tslint:disable */
/* eslint-disable */
/**
 * 
 * TIP-Rest Api v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RobjKommunikation
 */
export interface RobjKommunikation {
    /**
     * 
     * @type {string}
     * @memberof RobjKommunikation
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjKommunikation
     */
    'version'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjKommunikation
     */
    'artCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjKommunikation
     */
    'artDecode'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjKommunikation
     */
    'verbindung'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjKommunikation
     */
    'kzBevorzugt'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjKommunikation
     */
    'orgUser'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjKommunikation
     */
    'orgXPts'?: string;
}

