/* tslint:disable */
/* eslint-disable */
/**
 * 
 * TIP-Rest Api v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RobjSchulpersonal
 */
export interface RobjSchulpersonal {
    /**
     * 
     * @type {string}
     * @memberof RobjSchulpersonal
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjSchulpersonal
     */
    'version'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjSchulpersonal
     */
    'code'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjSchulpersonal
     */
    'decode'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjSchulpersonal
     */
    'ext1'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjSchulpersonal
     */
    'nachname'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjSchulpersonal
     */
    'vorname'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjSchulpersonal
     */
    'titel'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjSchulpersonal
     */
    'schuleId'?: string;
}

