/* tslint:disable */
/* eslint-disable */
/**
 * 
 * TIP-Rest Api v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RobjKurslehrerZuordnung
 */
export interface RobjKurslehrerZuordnung {
    /**
     * 
     * @type {string}
     * @memberof RobjKurslehrerZuordnung
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjKurslehrerZuordnung
     */
    'version'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjKurslehrerZuordnung
     */
    'KursId'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjKurslehrerZuordnung
     */
    'KurslehrerId'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjKurslehrerZuordnung
     */
    'KurslehrerName'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjKurslehrerZuordnung
     */
    'funktionsbezeichnungId'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjKurslehrerZuordnung
     */
    'funktionsbezeichnung'?: string;
}

