/* tslint:disable */
/* eslint-disable */
/**
 * 
 * TIP-Rest Api v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RobjTooltip
 */
export interface RobjTooltip {
    /**
     * 
     * @type {string}
     * @memberof RobjTooltip
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjTooltip
     */
    'version'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjTooltip
     */
    'komponente'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjTooltip
     */
    'feld'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjTooltip
     */
    'text'?: string;
}

