/* tslint:disable */
/* eslint-disable */
/**
 * 
 * TIP-Rest Api v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RobjDienststelle
 */
export interface RobjDienststelle {
    /**
     * 
     * @type {string}
     * @memberof RobjDienststelle
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjDienststelle
     */
    'version'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjDienststelle
     */
    'gepa_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjDienststelle
     */
    'GEPA_NAME_1'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjDienststelle
     */
    'gepa_ortv_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjDienststelle
     */
    'gepa_strv_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjDienststelle
     */
    'anschriftId'?: string;
}

