/* tslint:disable */
/* eslint-disable */
/**
 * 
 * TIP-Rest Api v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RobjKurslehrerZuordnung } from './robj-kurslehrer-zuordnung';

/**
 * 
 * @export
 * @interface RobjKurs
 */
export interface RobjKurs {
    /**
     * 
     * @type {string}
     * @memberof RobjKurs
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjKurs
     */
    'version'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjKurs
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjKurs
     */
    'schuleId'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjKurs
     */
    'halbjahrId'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjKurs
     */
    'halbjahrBeschreibung'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjKurs
     */
    'dtBeginn'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjKurs
     */
    'dtEnde'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjKurs
     */
    'schuelerAnzahl'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjKurs
     */
    'kzMeineKurs'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjKurs
     */
    'kzAktiv'?: string;
    /**
     * 
     * @type {Array<RobjKurslehrerZuordnung>}
     * @memberof RobjKurs
     */
    'listKurslehrer'?: Array<RobjKurslehrerZuordnung>;
}

