/* tslint:disable */
/* eslint-disable */
/**
 * 
 * TIP-Rest Api v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RobjSchule
 */
export interface RobjSchule {
    /**
     * 
     * @type {string}
     * @memberof RobjSchule
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjSchule
     */
    'version'?: string;
    /**
     * 
     * @type {number}
     * @memberof RobjSchule
     */
    'ROWS_TOTAL'?: number;
    /**
     * 
     * @type {string}
     * @memberof RobjSchule
     */
    'RESULTSET_ID'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjSchule
     */
    'schulnummer'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjSchule
     */
    'schulname'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjSchule
     */
    'schulartDecode'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjSchule
     */
    'ort'?: string;
    /**
     * 
     * @type {string}
     * @memberof RobjSchule
     */
    'strasse'?: string;
}

