
  - name: Configmap
    community.kubernetes.k8s:
      kubeconfig: ~/.kube/config
      namespace: "{{ NAMESPACE }}"
      template: configmap.yml.j2

  - name: Secret
    community.kubernetes.k8s:
      kubeconfig: ~/.kube/config
      namespace: "{{ NAMESPACE }}"
      template: secret.yml.j2
    when: ONEPASSWORD_OPERATOR is undefined or ONEPASSWORD_OPERATOR is defined and not ONEPASSWORD_OPERATOR

  - name: Secret by 1Password
    community.kubernetes.k8s:
      kubeconfig: ~/.kube/config
      namespace: "{{ NAMESPACE }}"
      template: onepassword.yml.j2
    when: ONEPASSWORD_OPERATOR is defined and ONEPASSWORD_OPERATOR|bool
