components:
  schemas:
    Facet:
      properties:
        facetCriteria:
          type: string
        facetValues:
          items:
            $ref: "#/components/schemas/FacetValue"
          type: array
      type: object
    FacetValue:
      properties:
        numberOfOccurrences:
          format: int32
          type: integer
        term:
          type: string
      type: object
    PageSchoolDTO:
      properties:
        items:
          items:
            $ref: "#/components/schemas/SchoolDTO"
          type: array
        lastPage:
          format: int64
          type: integer
        totalCount:
          format: int64
          type: integer
        pageSize:
          format: int64
          type: integer
        actions:
          additionalProperties:
            additionalProperties:
              type: string
            type: object
          type: object
        page:
          format: int64
          type: integer
        facets:
          items:
            $ref: "#/components/schemas/Facet"
          type: array
      type: object
    SchoolDTO:
      properties:
        organizationId:
          format: int64
          type: integer
        organizationName:
          type: string
        schoolAddress:
          type: string
        schoolAdminEmailAddress:
          type: string
        schoolCity:
          type: string
        schoolName:
          type: string
        schoolNameFromIdm:
          type: string
        schoolNumber:
          type: string
        schoolRegion:
          type: string
        schoolZipcode:
          type: string
        x-class-name:
          default: hu.webtown.liferay.vidis.rest.dto.v1_0.SchoolDTO
          readOnly: true
          type: string
      type: object
      xml:
        name: SchoolDTO
    OfferCategoryDTO:
      properties:
        category:
          items:
            type: string
          type: array
        competency:
          items:
            type: string
          type: array
        gradeLevel:
          items:
            type: string
          type: array
        schoolType:
          items:
            type: string
          type: array
        x-class-name:
          default: hu.webtown.liferay.vidis.rest.dto.v1_0.OfferCategoryDTO
          readOnly: true
          type: string
      type: object
      xml:
        name: OfferCategoryDTO
    SchoolActivationDTO:
      required:
        - date
        - regionName
      properties:
        date:
          type: string
          example: 01-01-2025
        regionName:
          type: string
          example: NI_00100
      type: object
      xml:
        name: SchoolActivationDTO
    OfferDTO:
      properties:
        educationProviderOrganizationId:
          format: int64
          type: integer
        educationProviderOrganizationName:
          type: string
        educationProviderUserEmail:
          type: string
        educationProviderUserId:
          format: int64
          type: integer
        educationProviderUserName:
          type: string
        offerCategories:
          $ref: "#/components/schemas/OfferCategoryDTO"
        offerDescription:
          type: string
        offerId:
          format: int64
          type: integer
        offerLink:
          type: string
        offerLogo:
          type: string
        offerLongTitle:
          type: string
        offerResourcePk:
          format: int64
          type: integer
        offerStatus:
          type: string
        offerTitle:
          type: string
        offerVersion:
          format: int32
          type: integer
        schoolActivations:
          items:
            $ref: "#/components/schemas/SchoolActivationDTO"
          type: array
        x-class-name:
          default: hu.webtown.liferay.vidis.rest.dto.v1_0.OfferDTO
          readOnly: true
          type: string
      type: object
      xml:
        name: OfferDTO
    PageOfferDTO:
      properties:
        items:
          items:
            $ref: "#/components/schemas/OfferDTO"
          type: array
        lastPage:
          format: int64
          type: integer
        totalCount:
          format: int64
          type: integer
        pageSize:
          format: int64
          type: integer
        actions:
          additionalProperties:
            additionalProperties:
              type: string
            type: object
          type: object
        page:
          format: int64
          type: integer
        facets:
          items:
            $ref: "#/components/schemas/Facet"
          type: array
      type: object
    ActivationDTO:
      properties:
        activationUserEmail:
          type: string
        generatedAVVLink:
          type: string
        offerId:
          format: int64
          type: integer
        offerTitle:
          type: string
        organizationId:
          format: int64
          type: integer
        organizationName:
          type: string
        schoolNameFromIdm:
          type: string
        schoolNumber:
          type: string
        x-class-name:
          default: hu.webtown.liferay.vidis.rest.dto.v1_0.ActivationDTO
          readOnly: true
          type: string
      type: object
      xml:
        name: ActivationDTO
    PageActivationDTO:
      properties:
        items:
          items:
            $ref: "#/components/schemas/ActivationDTO"
          type: array
        lastPage:
          format: int64
          type: integer
        totalCount:
          format: int64
          type: integer
        pageSize:
          format: int64
          type: integer
        actions:
          additionalProperties:
            additionalProperties:
              type: string
            type: object
          type: object
        page:
          format: int64
          type: integer
        facets:
          items:
            $ref: "#/components/schemas/Facet"
          type: array
      type: object
info:
  description: Vidis REST API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Vidis REST
  version: v1.0
openapi: 3.0.1
paths:
  /v1.0/activation/schools:
    get:
      description: List all schools, that has activated any of the owned offers.
      operationId: getSchools
      parameters:
        - in: query
          name: page
          schema:
            type: string
        - in: query
          name: pageSize
          schema:
            type: string
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageSchoolDTO"
            application/xml:
              schema:
                $ref: "#/components/schemas/PageSchoolDTO"
          description: default response
      tags:
        - EducationProvider
  /v1.0/activation/schools/{organizationId}/offers:
    get:
      description: List all owned offers, that has activated by the selected school.
      operationId: getOffersBySchool
      parameters:
        - in: path
          name: organizationId
          required: true
          schema:
            type: string
        - in: query
          name: page
          schema:
            type: string
        - in: query
          name: pageSize
          schema:
            type: string
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageOfferDTO"
            application/xml:
              schema:
                $ref: "#/components/schemas/PageOfferDTO"
          description: default response
      tags:
        - EducationProvider
  /v1.0/activation/details:
    get:
      description: List all the activation details for all owned offer.
      operationId: getActivations
      parameters:
        - in: query
          name: page
          schema:
            type: string
        - in: query
          name: pageSize
          schema:
            type: string
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageActivationDTO"
            application/xml:
              schema:
                $ref: "#/components/schemas/PageActivationDTO"
          description: default response
      tags:
        - EducationProvider
  /v1.0/activation/offers:
    get:
      description: List all owned offers, that has activated by any schools.
      operationId: getOffers
      parameters:
        - in: query
          name: page
          schema:
            type: string
        - in: query
          name: pageSize
          schema:
            type: string
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageOfferDTO"
            application/xml:
              schema:
                $ref: "#/components/schemas/PageOfferDTO"
          description: default response
      tags:
        - EducationProvider
  /v1.0/activation/offers/{offerId}/schools:
    get:
      description: List all schools, that has activated the selected owned offer.
      operationId: getSchoolsByOffer
      parameters:
        - in: path
          name: offerId
          required: true
          schema:
            type: string
        - in: query
          name: page
          schema:
            type: string
        - in: query
          name: pageSize
          schema:
            type: string
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageSchoolDTO"
            application/xml:
              schema:
                $ref: "#/components/schemas/PageSchoolDTO"
          description: default response
      tags:
        - EducationProvider
  /v1.0/activation/offers/{offerId}/schools/{organizationId}/details:
    get:
      description: >-
        List the activation details for a selected owned offer, that has
        activated by the selected school.
      operationId: getActivationByOfferAndSchool
      parameters:
        - in: path
          name: offerId
          required: true
          schema:
            type: string
        - in: path
          name: organizationId
          required: true
          schema:
            type: string
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ActivationDTO"
            application/xml:
              schema:
                $ref: "#/components/schemas/ActivationDTO"
          description: default response
      tags:
        - EducationProvider
  /v1.0/activation/schools/{organizationId}/offers/{offerId}/details:
    get:
      description: >-
        List the activation details for a selected school, that has activated
        the selected owned offer.
      operationId: getActivationBySchoolAndOffer
      parameters:
        - in: path
          name: organizationId
          required: true
          schema:
            type: string
        - in: path
          name: offerId
          required: true
          schema:
            type: string
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ActivationDTO"
            application/xml:
              schema:
                $ref: "#/components/schemas/ActivationDTO"
          description: default response
      tags:
        - EducationProvider
  /v1.0/offers/all:
    get:
      description: List all offers.
      operationId: getAllOffers
      parameters:
        - in: query
          name: page
          schema:
            type: string
        - in: query
          name: pageSize
          schema:
            type: string
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageOfferDTO"
            application/xml:
              schema:
                $ref: "#/components/schemas/PageOfferDTO"
          description: default response
      tags:
        - IDMBetreiber
  /v1.0/offers/activated/by-school/{schoolName}:
    get:
      description: List all offers, that has activated by the selected school.
      operationId: getActivatedOffersBySchool
      parameters:
        - in: path
          name: schoolName
          required: true
          schema:
            type: string
        - in: query
          name: page
          schema:
            type: string
        - in: query
          name: pageSize
          schema:
            type: string
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageOfferDTO"
            application/xml:
              schema:
                $ref: "#/components/schemas/PageOfferDTO"
          description: default response
      tags:
        - IDMBetreiber
  /v1.0/offers/activated/by-region/{regionName}:
    get:
      description: >-
        List all offers, that has activated by any schools in the selected
        region.
      operationId: getActivatedOffersByRegion
      parameters:
        - in: path
          name: regionName
          required: true
          schema:
            type: string
        - in: query
          name: page
          schema:
            type: string
        - in: query
          name: pageSize
          schema:
            type: string
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageOfferDTO"
            application/xml:
              schema:
                $ref: "#/components/schemas/PageOfferDTO"
          description: default response
      tags:
        - IDMBetreiber
  /v1.0/openapi.{type}:
    get:
      operationId: getOpenAPI
      parameters:
        - in: path
          name: type
          required: true
          schema:
            type: string
      responses:
        default:
          content:
            application/json: {}
            application/yaml: {}
          description: default response
servers:
  - url: https://service-stage.vidis.schule/o/vidis-rest/
