- name: ConfigMap
  kubernetes.core.k8s:
    kubeconfig: ~/.kube/config
    namespace: "{{ NAMESPACE }}"
    template: configmap.yml.j2
  when: WITH_NOTIFICATION_SERVER is defined and WITH_NOTIFICATION_SERVER|bool
  tags:
    - configmap

- name: 1Password Item
  kubernetes.core.k8s:
    kubeconfig: ~/.kube/config
    namespace: "{{ NAMESPACE }}"
    template: onepassword.yml.j2
  when:
    - ONEPASSWORD_OPERATOR is defined and ONEPASSWORD_OPERATOR|bool
    - WITH_NOTIFICATION_SERVER is defined and WITH_NOTIFICATION_SERVER|bool
  tags:
    - 1password

- name: External Secret
  kubernetes.core.k8s:
    kubeconfig: ~/.kube/config
    namespace: "{{ NAMESPACE }}"
    template: external-secret.yml.j2
    state: "{{ 'present' if (WITH_BRANCH_MONGO_DB_MANAGEMENT is defined and WITH_BRANCH_MONGO_DB_MANAGEMENT|bool) and (WITH_NOTIFICATION_SERVER is defined and WITH_NOTIFICATION_SERVER|bool) else 'absent' }}"
  when:
    - EXTERNAL_SECRETS_OPERATOR is defined and EXTERNAL_SECRETS_OPERATOR|bool
  tags:
    - 1password

- name: Deployment
  kubernetes.core.k8s:
    kubeconfig: ~/.kube/config
    namespace: "{{ NAMESPACE }}"
    template: deployment.yml.j2
  when: WITH_NOTIFICATION_SERVER is defined and WITH_NOTIFICATION_SERVER|bool
  tags:
    - deployment

- name: Service
  kubernetes.core.k8s:
    kubeconfig: ~/.kube/config
    namespace: "{{ NAMESPACE }}"
    template: svc.yml.j2
  when: WITH_NOTIFICATION_SERVER is defined and WITH_NOTIFICATION_SERVER|bool
  tags:
    - service

- name: Service Monitor
  kubernetes.core.k8s:
    kubeconfig: ~/.kube/config
    namespace: "{{ NAMESPACE }}"
    template: svc-monitor.yml.j2
  when: WITH_NOTIFICATION_SERVER is defined and WITH_NOTIFICATION_SERVER|bool
  tags:
    - prometheus

- name: Ingress
  kubernetes.core.k8s:
    kubeconfig: ~/.kube/config
    namespace: "{{ NAMESPACE }}"
    template: ingress.yml.j2
  when: WITH_NOTIFICATION_SERVER is defined and WITH_NOTIFICATION_SERVER|bool
  tags:
    - ingress

- name: Add notification-server default allow network policy
  kubernetes.core.k8s:
    kubeconfig: ~/.kube/config
    namespace: "{{ NAMESPACE }}"
    template: default-allow-networkpolicy.yml.j2
  tags:
    - networkPolicy
