export interface ToolConfig {
	CTL_TOOLS__EXTERNAL_TOOL_MAX_LOGO_SIZE_IN_BYTES: number;
	CTL_TOOLS_BACKEND_URL: string;
	FEATURE_CTL_TOOLS_COPY_ENABLED: boolean;
	CTL_TOOLS_RELOAD_TIME_MS: number;
	CTL_TOOLS__PREFERRED_TOOLS_LIMIT: number;
	FEATURE_PREFERRED_CTL_TOOLS_ENABLED: boolean;
	PUBLIC_BACKEND_URL: string;
	FEATURE_VIDIS_MEDIA_ACTIVATIONS_ENABLED: boolean;
	FEATURE_SCHULCONNEX_MEDIA_LICENSE_ENABLED: boolean;
}
