export interface ToolConfig {
	FEATURE_CTL_TOOLS_TAB_ENABLED: boolean;
	FEATURE_LTI_TOOLS_TAB_ENABLED: boolean;
	CTL_TOOLS__EXTERNAL_TOOL_MAX_LOGO_SIZE_IN_BYTES: number;
	CTL_TOOLS_BACKEND_URL: string;
	FEATURE_CTL_TOOLS_COPY_ENABLED: boolean;
	CTL_TOOLS_RELOAD_TIME_MS: number;
	FILES_STORAGE__SERVICE_BASE_URL: string;
}
