###
# curl -u -H OCS-APIRequest:true -H Accept:application/json https://nextcloud-nbc.dbildungscloud.dev//ocs/v1.php/cloud/groups?search=SchulcloudNextcloud-5e1dc275322ce040a850b14b&format=json
GET https://nextcloud-nbc.dbildungscloud.dev/ocs/v1.php/cloud/groups?search=Test
Authorization: Basic capcakes {{CAPCAKESPASS}}
OCS-APIRequest: true
Accept: application/json
###
# curl -u -H OCS-APIRequest:true -H Accept:application/json https://nextcloud-nbc.dbildungscloud.dev/apps/groupfolders/folders
GET https://nextcloud-nbc.dbildungscloud.dev/apps/groupfolders/folders
Authorization: Basic capcakes {{CAPCAKESPASS}}
OCS-APIRequest: true
Accept: application/json
###
