/*
	This permission set is based on the current state of dBildungscloud.
	Last Update: 2023-03-21
*/
import { Permission } from '@shared/domain/interface';

export const userPermissions = [
	Permission.BASE_VIEW,
	Permission.DASHBOARD_VIEW,
	Permission.TOOL_VIEW,
	Permission.HOMEWORK_CREATE,
	Permission.PASSWORD_EDIT,
	Permission.FOLDER_DELETE,
	Permission.FOLDER_CREATE,
	Permission.FILE_DELETE,
	Permission.FILE_CREATE,
	Permission.FILE_MOVE,
	Permission.ACCOUNT_EDIT,
	Permission.CALENDAR_VIEW,
	Permission.CALENDAR_EDIT,
	Permission.CALENDAR_CREATE,
	Permission.FEDERALSTATE_VIEW,
	Permission.HELPDESK_CREATE,
	Permission.TOPIC_VIEW,
	Permission.LINK_CREATE,
	Permission.NEWS_VIEW,
	Permission.NOTIFICATION_VIEW,
	Permission.NOTIFICATION_EDIT,
	Permission.NOTIFICATION_CREATE,
	Permission.PWRECOVERY_VIEW,
	Permission.PWRECOVERY_EDIT,
	Permission.PWRECOVERY_CREATE,
	Permission.RELEASES_VIEW,
	Permission.ROLE_VIEW,
	Permission.COURSEGROUP_CREATE,
	Permission.COURSEGROUP_EDIT,
	Permission.SYSTEM_VIEW,
	Permission.HOMEWORK_VIEW,
	Permission.HOMEWORK_EDIT,
	Permission.COMMENTS_VIEW,
	Permission.COMMENTS_CREATE,
	Permission.COMMENTS_EDIT,
	Permission.SUBMISSIONS_VIEW,
	Permission.SUBMISSIONS_CREATE,
	Permission.SUBMISSIONS_EDIT,
	Permission.FILESTORAGE_VIEW,
	Permission.FILESTORAGE_EDIT,
	Permission.FILESTORAGE_CREATE,
	Permission.FILESTORAGE_WRITE_SCHOOL,
	Permission.CONTENT_VIEW,
	Permission.CONTENT_NON_OER_VIEW,
	Permission.FILESTORAGE_REMOVE,
	Permission.TEAM_VIEW,
	Permission.CLASS_VIEW,
	Permission.COURSE_VIEW,
	Permission.LERNSTORE_VIEW,
	Permission.GROUP_VIEW,
];

export const studentPermissions = [
	...userPermissions,
	Permission.TASK_DASHBOARD_VIEW_V3,
	Permission.TEAM_EDIT,
	Permission.TEAM_CREATE,
	Permission.JOIN_MEETING,
	Permission.TOOL_CREATE_ETHERPAD,
];

const sharedAdminPermissions = [
	Permission.ACCOUNT_CREATE,
	Permission.CLASS_CREATE,
	Permission.CLASS_EDIT,
	Permission.CLASS_LIST,
	Permission.CLASS_REMOVE,
	Permission.COURSE_CREATE,
	Permission.COURSE_EDIT,
	Permission.COURSE_REMOVE,
	Permission.GROUP_LIST,
	Permission.NEWS_CREATE,
	Permission.NEWS_EDIT,
	Permission.STUDENT_SKIP_REGISTRATION,
	Permission.SUBMISSIONS_SCHOOL_VIEW,
	Permission.TEACHER_LIST,
	Permission.TEAM_INVITE_EXTERNAL,
	Permission.STUDENT_EDIT,
	Permission.STUDENT_LIST,
	Permission.TEAM_EDIT,
	Permission.TEAM_CREATE,
];

export const teacherPermissions = [
	...userPermissions,
	...sharedAdminPermissions,
	// shared with student
	Permission.TASK_DASHBOARD_TEACHER_VIEW_V3,
	// New permissions
	Permission.LESSONS_VIEW,
	Permission.REQUEST_CONSENTS,
	Permission.SCHOOL_NEWS_EDIT,
	Permission.TOOL_CREATE,
	Permission.TOOL_EDIT,
	Permission.TOOL_NEW_VIEW,
	Permission.TOPIC_CREATE,
	Permission.TOPIC_EDIT,
	Permission.START_MEETING,
	Permission.CONTEXT_TOOL_ADMIN,
];

export const adminPermissions = [
	...userPermissions,
	...sharedAdminPermissions,
	Permission.ADMIN_VIEW,
	Permission.CLASS_FULL_ADMIN,
	Permission.DATASOURCES_CREATE,
	Permission.DATASOURCES_DELETE,
	Permission.DATASOURCES_EDIT,
	Permission.DATASOURCES_RUN,
	Permission.DATASOURCES_RUN_VIEW,
	Permission.DATASOURCES_VIEW,
	Permission.HELPDESK_EDIT,
	Permission.HELPDESK_VIEW,
	Permission.REQUEST_CONSENTS,
	Permission.SCHOOL_EDIT,
	Permission.SCHOOL_NEWS_EDIT,
	Permission.STUDENT_CREATE,
	Permission.STUDENT_DELETE,
	Permission.SYSTEM_CREATE,
	Permission.TEACHER_CREATE,
	Permission.TEACHER_DELETE,
	Permission.TEACHER_EDIT,
	Permission.TEACHER_SKIP_REGISTRATION,
	Permission.SCHOOL_LOGO_MANAGE,
	Permission.SCHOOL_CHAT_MANAGE,
	Permission.SCHOOL_STUDENT_TEAM_MANAGE,
	Permission.SCHOOL_SYSTEM_EDIT,
	Permission.SCHOOL_SYSTEM_VIEW,
	Permission.SYSTEM_EDIT,
	Permission.SYNC_START,
	Permission.SCHOOL_PERMISSION_VIEW,
	Permission.SCHOOL_PERMISSION_CHANGE,
	Permission.IMPORT_USER_MIGRATE,
	Permission.IMPORT_USER_UPDATE,
	Permission.IMPORT_USER_VIEW,
	Permission.SCHOOL_TOOL_ADMIN,
	Permission.GROUP_FULL_ADMIN,
	Permission.USER_LOGIN_MIGRATION_ADMIN,
];

export const superheroPermissions = [Permission.USER_LOGIN_MIGRATION_ROLLBACK, Permission.FILESTORAGE_WRITE_INSTANCE];
