/* tslint:disable */
/* eslint-disable */
/**
 * Schulcloud-Verbund-Software Server API
 * This is v3 of Schulcloud-Verbund-Software Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { CollaborativeTextEditorElementResponse } from './collaborative-text-editor-element-response';
// May contain unused imports in some cases
// @ts-ignore
import type { ContentElementType } from './content-element-type';
// May contain unused imports in some cases
// @ts-ignore
import type { DeletedElementResponse } from './deleted-element-response';
// May contain unused imports in some cases
// @ts-ignore
import type { DrawingElementResponse } from './drawing-element-response';
// May contain unused imports in some cases
// @ts-ignore
import type { ExternalToolElementResponse } from './external-tool-element-response';
// May contain unused imports in some cases
// @ts-ignore
import type { FileElementResponse } from './file-element-response';
// May contain unused imports in some cases
// @ts-ignore
import type { FileFolderElementResponse } from './file-folder-element-response';
// May contain unused imports in some cases
// @ts-ignore
import type { H5pElementContent } from './h5p-element-content';
// May contain unused imports in some cases
// @ts-ignore
import type { H5pElementResponse } from './h5p-element-response';
// May contain unused imports in some cases
// @ts-ignore
import type { LinkElementResponse } from './link-element-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RichTextElementResponse } from './rich-text-element-response';
// May contain unused imports in some cases
// @ts-ignore
import type { SubmissionContainerElementResponse } from './submission-container-element-response';
// May contain unused imports in some cases
// @ts-ignore
import type { TimestampsResponse } from './timestamps-response';
// May contain unused imports in some cases
// @ts-ignore
import type { VideoConferenceElementResponse } from './video-conference-element-response';

/**
 * @type CardResponseElementsInner
 * @export
 */
export type CardResponseElementsInner =
	| CollaborativeTextEditorElementResponse
	| DeletedElementResponse
	| DrawingElementResponse
	| ExternalToolElementResponse
	| FileElementResponse
	| FileFolderElementResponse
	| H5pElementResponse
	| LinkElementResponse
	| RichTextElementResponse
	| SubmissionContainerElementResponse
	| VideoConferenceElementResponse;
