export const enum DeletionDomainModel {
	ACCOUNT = 'account',
	CLASS = 'class',
	COURSEGROUP = 'courseGroup',
	COURSE = 'course',
	DASHBOARD = 'dashboard',
	FILE = 'file',
	FILERECORDS = 'fileRecords',
	LESSONS = 'lessons',
	PSEUDONYMS = 'pseudonyms',
	REGISTRATIONPIN = 'registrationPin',
	ROCKETCHATUSER = 'rocketChatUser',
	TEAMS = 'teams',
	USER = 'user',
}
