export enum DomainName {
	ACCOUNT = 'account',
	BOARD = 'board',
	CLASS = 'class',
	COURSEGROUP = 'courseGroup',
	COURSE = 'course',
	DASHBOARD = 'dashboard',
	FILE = 'file',
	FILERECORDS = 'fileRecords',
	GROUP = 'group',
	LESSONS = 'lessons',
	PSEUDONYMS = 'pseudonyms',
	REGISTRATIONPIN = 'registrationPin',
	ROCKETCHATUSER = 'rocketChatUser',
	ROCKETCHATSERVICE = 'rocketChatService',
	TASK = 'task',
	TEAMS = 'teams',
	USER = 'user',
	SUBMISSIONS = 'submissions',
	NEWS = 'news',
	CALENDAR = 'calendar',
	ROOM = 'room',
}
