export enum RoomColor {
	BLUE_GREY = 'blue-grey',
	PINK = 'pink',
	RED = 'red',
	ORANGE = 'orange',
	YELLOW = 'yellow',
	OLIVE = 'olive',
	GREEN = 'green',
	TURQUOISE = 'turquoise',
	LIGHT_BLUE = 'light-blue',
	BLUE = 'blue',
	MAGENTA = 'magenta',
	PURPLE = 'purple',
	BROWN = 'brown',
}
