/* tslint:disable */
/* eslint-disable */
/**
 * Etherpad API
 * Etherpad is a real-time collaborative editor scalable to thousands of simultaneous real time users. It provides full data export capabilities, and runs on your server, under your control.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ListSessionsOfGroupUsingGET200ResponseData } from './list-sessions-of-group-using-get200-response-data';

/**
 * 
 * @export
 * @interface ListSessionsOfGroupUsingGET200Response
 */
export interface ListSessionsOfGroupUsingGET200Response {
    /**
     * 
     * @type {number}
     * @memberof ListSessionsOfGroupUsingGET200Response
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof ListSessionsOfGroupUsingGET200Response
     */
    'message'?: string;
    /**
     * 
     * @type {ListSessionsOfGroupUsingGET200ResponseData}
     * @memberof ListSessionsOfGroupUsingGET200Response
     */
    'data'?: ListSessionsOfGroupUsingGET200ResponseData;
}

