/* tslint:disable */
/* eslint-disable */
/**
 * Etherpad API
 * Etherpad is a real-time collaborative editor scalable to thousands of simultaneous real time users. It provides full data export capabilities, and runs on your server, under your control.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetSessionInfoUsingGET200ResponseDataInfo } from './get-session-info-using-get200-response-data-info';

/**
 * 
 * @export
 * @interface ListSessionsOfGroupUsingGET200ResponseData
 */
export interface ListSessionsOfGroupUsingGET200ResponseData {
    /**
     * 
     * @type {Array<GetSessionInfoUsingGET200ResponseDataInfo>}
     * @memberof ListSessionsOfGroupUsingGET200ResponseData
     */
    'sessions'?: Array<GetSessionInfoUsingGET200ResponseDataInfo>;
}

