/* tslint:disable */
/* eslint-disable */
/**
 * Etherpad API
 * Etherpad is a real-time collaborative editor scalable to thousands of simultaneous real time users. It provides full data export capabilities, and runs on your server, under your control.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SessionInfo
 */
export interface SessionInfo {
    /**
     * 
     * @type {string}
     * @memberof SessionInfo
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof SessionInfo
     */
    'authorID'?: string;
    /**
     * 
     * @type {string}
     * @memberof SessionInfo
     */
    'groupID'?: string;
    /**
     * 
     * @type {number}
     * @memberof SessionInfo
     */
    'validUntil'?: number;
}

