galaxy_info:
  role_name: moin-schule-sync
  author: Schul-Cloud Verbund
  description: moin-schule-sync role for the moin.schule synchronization purposes
  company: Schul-Cloud Verbund
  license: license (AGPLv3)
  min_ansible_version: 2.8
  galaxy_tags: []
dependencies: []
