export interface ProvisioningConfig {
	FEATURE_SCHULCONNEX_COURSE_SYNC_ENABLED: boolean;
	FEATURE_SCHULCONNEX_MEDIA_LICENSE_ENABLED: boolean;
	PROVISIONING_SCHULCONNEX_POLICIES_INFO_URL: string;
	PROVISIONING_SCHULCONNEX_GROUP_USERS_LIMIT?: number;
	FEATURE_SCHULCONNEX_GROUP_PROVISIONING_ENABLED: boolean;
	FEATURE_OTHER_GROUPUSERS_PROVISIONING_ENABLED: boolean;
	SCHULCONNEX_COURSE_SYNC_HISTORY_EXPIRATION_SECONDS: number;
	FEATURE_SCHULCONNEX_EXTERNAL_PERSONS: boolean;
}
