export interface ProvisioningConfig {
	FEATURE_SCHULCONNEX_COURSE_SYNC_ENABLED: boolean;
	FEATURE_SCHULCONNEX_MEDIA_LICENSE_ENABLED: boolean;
	PROVISIONING_SCHULCONNEX_POLICIES_INFO_URL: string;
	FEATURE_SANIS_GROUP_PROVISIONING_ENABLED: boolean;
	FEATURE_OTHER_GROUPUSERS_PROVISIONING_ENABLED: boolean;
}
