export enum ErrorType {
	FILE_IS_BLOCKED = 'FILE_IS_BLOCKED',
	FILE_NOT_FOUND = 'FILE_NOT_FOUND',
	FILE_NAME_EXISTS = 'FILE_NAME_EXISTS',
	FILE_NAME_EMPTY = 'FILE_NAME_EMPTY',
	COULD_NOT_CREATE_PATH = 'COULD_NOT_CREATE_PATH',
}
