export * from './base.entity';
export * from './consent';
export * from './news.entity';
export * from './role.entity';
export * from './storageprovider.entity';
export * from './submission.entity';
export * from './task.entity';
export * from './team.entity';
export * from './video-conference.entity';
