export enum RoleNames {
	ADMINISTRATOR = 'administrator',
	COURSEADMINISTRATOR = 'courseAdministrator',
	COURSESTUDENT = 'courseStudent',
	COURSESUBSTITUTIONTEACHER = 'courseSubstitutionTeacher',
	COURSETEACHER = 'courseTeacher',
	DEMO = 'demo',
	DEMOSTUDENT = 'demoStudent',
	DEMOTEACHER = 'demoTeacher',
	EXPERT = 'expert',
	HELPDESK = 'helpdesk',
	STUDENT = 'student',
	SUPERHERO = 'superhero',
	TEACHER = 'teacher',
	TEAMADMINISTRATOR = 'teamadministrator',
	TEAMEXPERT = 'teamexpert',
	TEAMLEADER = 'teamleader',
	TEAMMEMBER = 'teammember',
	TEAMOWNER = 'teamowner',
	USER = 'user',
}
