security:
  - jwtBearer: []
info:
  title: Schul-Cloud Videoconference Service API
  description:
    This is the API specification for the Schul-Cloud Videoconference service.
    
  contact:
    name: support
    email: info@hpi-schul-cloud.de
  license:
    name: GPL-3.0
    url: 'https://github.com/hpi-schul-cloud/schulcloud-server/blob/master/LICENSE'
  version: 1.0.0
components:
  securitySchemes:
    jwtBearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    videoconference:
      description: TODO
    scopeName:
      description: TODO

paths:
  /videoconference:
    post:
      parameters: []
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/videoconference'
        '401':
          description: not authenticated
        '500':
          description: general error
      description: Creates a new resource with data.
      summary: ''
      tags:
        - videoconference
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/videoconference'
  '/videoconference/{scopeName}/{id}':
    get:
      parameters:
        - in: path
          name: scopeName
          schema:
            type: string
          required: true
          description: scopeName parameter
        - in: path
          name: id
          description: 'ID of :scopeName to return'
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/scopeName'
        '401':
          description: not authenticated
        '404':
          description: not found
        '500':
          description: general error
      description: Retrieves a single resource with the given id from the service.
      summary: ''
      tags:
        - videoconference
      security: []
  
openapi: 3.0.2
tags:
  - name: videoconference
    description: A videoconference service.
