export interface UserLoginMigrationConfig {
	MIGRATION_END_GRACE_PERIOD_MS: number;
	FEATURE_USER_LOGIN_MIGRATION_ENABLED: boolean;
	FEATURE_MIGRATION_WIZARD_WITH_USER_LOGIN_MIGRATION: boolean;
	FEATURE_SHOW_MIGRATION_WIZARD: boolean;
	FEATURE_SHOW_OUTDATED_USERS: boolean;
}
