- name: Configmap
  kubernetes.core.k8s:
    kubeconfig: ~/.kube/config
    namespace: '{{ NAMESPACE }}'
    template: configmap.yml.j2
  when: WITH_LEGACY_FILE_ARCHIVE is defined and WITH_LEGACY_FILE_ARCHIVE|bool
  tags:
    - configmap

- name: Deployment
  kubernetes.core.k8s:
    kubeconfig: ~/.kube/config
    namespace: '{{ NAMESPACE }}'
    template: deployment.yml.j2
  when: WITH_LEGACY_FILE_ARCHIVE is defined and WITH_LEGACY_FILE_ARCHIVE|bool
  tags:
    - deployment

- name: Service
  kubernetes.core.k8s:
    kubeconfig: ~/.kube/config
    namespace: '{{ NAMESPACE }}'
    template: svc.yml.j2
  when: WITH_LEGACY_FILE_ARCHIVE is defined and WITH_LEGACY_FILE_ARCHIVE|bool
  tags:
    - service

- name: Ingress
  kubernetes.core.k8s:
    kubeconfig: ~/.kube/config
    namespace: '{{ NAMESPACE }}'
    template: ingress.yml.j2
  when: WITH_LEGACY_FILE_ARCHIVE is defined and WITH_LEGACY_FILE_ARCHIVE|bool
  tags:
    - ingress

- name: Legacy File Archive pod monitor
  kubernetes.core.k8s:
    kubeconfig: ~/.kube/config
    namespace: '{{ NAMESPACE }}'
    template: pod-monitor.yml.j2
    state: 'present'
  when: WITH_LEGACY_FILE_ARCHIVE is defined and WITH_LEGACY_FILE_ARCHIVE|bool
  tags:
    - prometheus
