/* tslint:disable */
/* eslint-disable */
/**
 * Schulcloud-Verbund-Software Server API
 * This is v3 of Schulcloud-Verbund-Software Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AccountByIdBodyParams
 */
export interface AccountByIdBodyParams {
    /**
     * The new user name for the user.
     * @type {string}
     * @memberof AccountByIdBodyParams
     */
    'username'?: string | null;
    /**
     * The new password for the user.
     * @type {string}
     * @memberof AccountByIdBodyParams
     */
    'password'?: string | null;
    /**
     * The new activation state of the user.
     * @type {boolean}
     * @memberof AccountByIdBodyParams
     */
    'activated'?: boolean | null;
}

