/* tslint:disable */
/* eslint-disable */
/**
 * Schulcloud-Verbund-Software Server API
 * This is v3 of Schulcloud-Verbund-Software Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiValidationError
 */
export interface ApiValidationError {
    /**
     * The response status code.
     * @type {number}
     * @memberof ApiValidationError
     */
    'code': number;
    /**
     * The error type.
     * @type {string}
     * @memberof ApiValidationError
     */
    'type': string;
    /**
     * The error title.
     * @type {string}
     * @memberof ApiValidationError
     */
    'title': string;
    /**
     * The error message.
     * @type {string}
     * @memberof ApiValidationError
     */
    'message': string;
    /**
     * The error details.
     * @type {object}
     * @memberof ApiValidationError
     */
    'details'?: object;
}

