/* tslint:disable */
/* eslint-disable */
/**
 * Schulcloud-Verbund-Software Server API
 * This is v3 of Schulcloud-Verbund-Software Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ContextExternalToolCountPerContextResponse
 */
export interface ContextExternalToolCountPerContextResponse {
    /**
     * 
     * @type {number}
     * @memberof ContextExternalToolCountPerContextResponse
     */
    'course': number;
    /**
     * 
     * @type {number}
     * @memberof ContextExternalToolCountPerContextResponse
     */
    'boardElement': number;
    /**
     * 
     * @type {number}
     * @memberof ContextExternalToolCountPerContextResponse
     */
    'mediaBoard': number;
}

