/* tslint:disable */
/* eslint-disable */
/**
 * Schulcloud-Verbund-Software Server API
 * This is v3 of Schulcloud-Verbund-Software Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BasicToolConfigParams } from './basic-tool-config-params';
// May contain unused imports in some cases
// @ts-ignore
import type { Lti11ToolConfigCreateParams } from './lti11-tool-config-create-params';
// May contain unused imports in some cases
// @ts-ignore
import type { LtiMessageType } from './lti-message-type';
// May contain unused imports in some cases
// @ts-ignore
import type { LtiPrivacyPermission } from './lti-privacy-permission';
// May contain unused imports in some cases
// @ts-ignore
import type { Oauth2ToolConfigCreateParams } from './oauth2-tool-config-create-params';

/**
 * @type ExternalToolResponseConfig
 * Configuration of the external tool
 * @export
 */
export type ExternalToolResponseConfig = BasicToolConfigParams | Lti11ToolConfigCreateParams | Oauth2ToolConfigCreateParams;


