/* tslint:disable */
/* eslint-disable */
/**
 * Schulcloud-Verbund-Software Server API
 * This is v3 of Schulcloud-Verbund-Software Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MetaTagExtractorResponse
 */
export interface MetaTagExtractorResponse {
    /**
     * 
     * @type {string}
     * @memberof MetaTagExtractorResponse
     */
    'url': string;
    /**
     * 
     * @type {string}
     * @memberof MetaTagExtractorResponse
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof MetaTagExtractorResponse
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof MetaTagExtractorResponse
     */
    'imageUrl': string;
    /**
     * 
     * @type {string}
     * @memberof MetaTagExtractorResponse
     */
    'type': string;
    /**
     * 
     * @type {string}
     * @memberof MetaTagExtractorResponse
     */
    'parentTitle': string;
    /**
     * 
     * @type {string}
     * @memberof MetaTagExtractorResponse
     */
    'parentType': string;
}

