/* tslint:disable */
/* eslint-disable */
/**
 * Schulcloud-Verbund-Software Server API
 * This is v3 of Schulcloud-Verbund-Software Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OauthConfigResponse
 */
export interface OauthConfigResponse {
    /**
     * Client id
     * @type {string}
     * @memberof OauthConfigResponse
     */
    'clientId': string;
    /**
     * Hint for idp redirects (optional)
     * @type {string}
     * @memberof OauthConfigResponse
     */
    'idpHint'?: string | null;
    /**
     * Redirect uri
     * @type {string}
     * @memberof OauthConfigResponse
     */
    'redirectUri': string;
    /**
     * Grant type
     * @type {string}
     * @memberof OauthConfigResponse
     */
    'grantType': string;
    /**
     * Token endpoint
     * @type {string}
     * @memberof OauthConfigResponse
     */
    'tokenEndpoint': string;
    /**
     * Auth endpoint
     * @type {string}
     * @memberof OauthConfigResponse
     */
    'authEndpoint': string;
    /**
     * Response type
     * @type {string}
     * @memberof OauthConfigResponse
     */
    'responseType': string;
    /**
     * Scope
     * @type {string}
     * @memberof OauthConfigResponse
     */
    'scope': string;
    /**
     * Provider
     * @type {string}
     * @memberof OauthConfigResponse
     */
    'provider': string;
    /**
     * Logout endpoint
     * @type {string}
     * @memberof OauthConfigResponse
     */
    'logoutEndpoint'?: string;
    /**
     * Issuer
     * @type {string}
     * @memberof OauthConfigResponse
     */
    'issuer': string;
    /**
     * Jwks endpoint
     * @type {string}
     * @memberof OauthConfigResponse
     */
    'jwksEndpoint': string;
}

