/* tslint:disable */
/* eslint-disable */
/**
 * Schulcloud-Verbund-Software Server API
 * This is v3 of Schulcloud-Verbund-Software Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OidcContextResponse
 */
export interface OidcContextResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof OidcContextResponse
     */
    'acr_values': Array<string>;
    /**
     * 
     * @type {string}
     * @memberof OidcContextResponse
     */
    'display': string;
    /**
     * 
     * @type {object}
     * @memberof OidcContextResponse
     */
    'id_token_hint_claims': object;
    /**
     * 
     * @type {string}
     * @memberof OidcContextResponse
     */
    'login_hint': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof OidcContextResponse
     */
    'ui_locales': Array<string>;
}

