/* tslint:disable */
/* eslint-disable */
/**
 * Schulcloud-Verbund-Software Server API
 * This is v3 of Schulcloud-Verbund-Software Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ParentConsentResponse
 */
export interface ParentConsentResponse {
    /**
     * 
     * @type {string}
     * @memberof ParentConsentResponse
     */
    'form': string;
    /**
     * 
     * @type {boolean}
     * @memberof ParentConsentResponse
     */
    'privacyConsent': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ParentConsentResponse
     */
    'termsOfUseConsent': boolean;
    /**
     * 
     * @type {string}
     * @memberof ParentConsentResponse
     */
    'dateOfPrivacyConsent': string;
    /**
     * 
     * @type {string}
     * @memberof ParentConsentResponse
     */
    'dateOfTermsOfUseConsent': string;
    /**
     * 
     * @type {string}
     * @memberof ParentConsentResponse
     */
    '_id': string;
}

