/* tslint:disable */
/* eslint-disable */
/**
 * Schulcloud-Verbund-Software Server API
 * This is v3 of Schulcloud-Verbund-Software Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const SchulcloudTheme = {
    BRB: 'brb',
    DEFAULT: 'default',
    N21: 'n21',
    THR: 'thr'
} as const;

export type SchulcloudTheme = typeof SchulcloudTheme[keyof typeof SchulcloudTheme];



