/* tslint:disable */
/* eslint-disable */
/**
 * Schulcloud-Verbund-Software Server API
 * This is v3 of Schulcloud-Verbund-Software Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ToolLaunchRequestResponse
 */
export interface ToolLaunchRequestResponse {
    /**
     * The Launch Request method (GET or POST)
     * @type {string}
     * @memberof ToolLaunchRequestResponse
     */
    'method': ToolLaunchRequestResponseMethod;
    /**
     * The URL for the Tool Launch Request
     * @type {string}
     * @memberof ToolLaunchRequestResponse
     */
    'url': string;
    /**
     * The payload for the Tool Launch Request (optional)
     * @type {string}
     * @memberof ToolLaunchRequestResponse
     */
    'payload'?: string;
    /**
     * Specifies whether the Tool should be launched in a new tab
     * @type {boolean}
     * @memberof ToolLaunchRequestResponse
     */
    'openNewTab'?: boolean;
}

export const ToolLaunchRequestResponseMethod = {
    GET: 'GET',
    POST: 'POST'
} as const;

export type ToolLaunchRequestResponseMethod = typeof ToolLaunchRequestResponseMethod[keyof typeof ToolLaunchRequestResponseMethod];


