export enum ErrorType {
	FILE_IS_BLOCKED = 'FILE_IS_BLOCKED',
	FILE_NOT_FOUND = 'FILE_NOT_FOUND',
	FILE_NAME_EXISTS = 'FILE_NAME_EXISTS',
	FILE_NAME_EMPTY = 'FILE_NAME_EMPTY',
	COULD_NOT_CREATE_PATH = 'COULD_NOT_CREATE_PATH',
	FILE_TOO_BIG = 'FILE_TOO_BIG',
	PREVIEW_NOT_POSSIBLE = 'PREVIEW_NOT_POSSIBLE',
	FILE_IS_EMPTY = 'FILE_IS_EMPTY',
}
