/* tslint:disable */
/* eslint-disable */
/**
 * Etherpad API
 * Etherpad is a real-time collaborative editor scalable to thousands of simultaneous real time users. It provides full data export capabilities, and runs on your server, under your control.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateAuthorUsingGET200Response } from '../models';
// @ts-ignore
import type { CreateGroupUsingGET400Response } from '../models';
// @ts-ignore
import type { CreateGroupUsingGET401Response } from '../models';
// @ts-ignore
import type { CreateGroupUsingGET500Response } from '../models';
// @ts-ignore
import type { GetAuthorNameUsingGET200Response } from '../models';
// @ts-ignore
import type { ListPadsUsingGET200Response } from '../models';
// @ts-ignore
import type { ListSessionsOfGroupUsingGET200Response } from '../models';
/**
 * AuthorApi - axios parameter creator
 * @export
 */
export const AuthorApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary this functions helps you to map your application author ids to Etherpad author ids
         * @param {string} [authorMapper] 
         * @param {string} [name] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAuthorIfNotExistsForUsingGET: async (authorMapper?: string, name?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/createAuthorIfNotExistsFor`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            await setApiKeyToObject(localVarQueryParameter, "apikey", configuration)

            if (authorMapper !== undefined) {
                localVarQueryParameter['authorMapper'] = authorMapper;
            }

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary this functions helps you to map your application author ids to Etherpad author ids
         * @param {string} [authorMapper] 
         * @param {string} [name] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAuthorIfNotExistsForUsingPOST: async (authorMapper?: string, name?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/createAuthorIfNotExistsFor`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            await setApiKeyToObject(localVarQueryParameter, "apikey", configuration)

            if (authorMapper !== undefined) {
                localVarQueryParameter['authorMapper'] = authorMapper;
            }

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary creates a new author
         * @param {string} [name] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAuthorUsingGET: async (name?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/createAuthor`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            await setApiKeyToObject(localVarQueryParameter, "apikey", configuration)

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary creates a new author
         * @param {string} [name] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAuthorUsingPOST: async (name?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/createAuthor`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            await setApiKeyToObject(localVarQueryParameter, "apikey", configuration)

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Returns the Author Name of the author
         * @param {string} [authorID] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAuthorNameUsingGET: async (authorID?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/getAuthorName`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            await setApiKeyToObject(localVarQueryParameter, "apikey", configuration)

            if (authorID !== undefined) {
                localVarQueryParameter['authorID'] = authorID;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Returns the Author Name of the author
         * @param {string} [authorID] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAuthorNameUsingPOST: async (authorID?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/getAuthorName`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            await setApiKeyToObject(localVarQueryParameter, "apikey", configuration)

            if (authorID !== undefined) {
                localVarQueryParameter['authorID'] = authorID;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary returns an array of all pads this author contributed to
         * @param {string} [authorID] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPadsOfAuthorUsingGET: async (authorID?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/listPadsOfAuthor`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            await setApiKeyToObject(localVarQueryParameter, "apikey", configuration)

            if (authorID !== undefined) {
                localVarQueryParameter['authorID'] = authorID;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary returns an array of all pads this author contributed to
         * @param {string} [authorID] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPadsOfAuthorUsingPOST: async (authorID?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/listPadsOfAuthor`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            await setApiKeyToObject(localVarQueryParameter, "apikey", configuration)

            if (authorID !== undefined) {
                localVarQueryParameter['authorID'] = authorID;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary returns all sessions of an author
         * @param {string} [authorID] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSessionsOfAuthorUsingGET: async (authorID?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/listSessionsOfAuthor`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            await setApiKeyToObject(localVarQueryParameter, "apikey", configuration)

            if (authorID !== undefined) {
                localVarQueryParameter['authorID'] = authorID;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary returns all sessions of an author
         * @param {string} [authorID] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSessionsOfAuthorUsingPOST: async (authorID?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/listSessionsOfAuthor`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            await setApiKeyToObject(localVarQueryParameter, "apikey", configuration)

            if (authorID !== undefined) {
                localVarQueryParameter['authorID'] = authorID;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthorApi - functional programming interface
 * @export
 */
export const AuthorApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthorApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary this functions helps you to map your application author ids to Etherpad author ids
         * @param {string} [authorMapper] 
         * @param {string} [name] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createAuthorIfNotExistsForUsingGET(authorMapper?: string, name?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateAuthorUsingGET200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createAuthorIfNotExistsForUsingGET(authorMapper, name, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthorApi.createAuthorIfNotExistsForUsingGET']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary this functions helps you to map your application author ids to Etherpad author ids
         * @param {string} [authorMapper] 
         * @param {string} [name] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createAuthorIfNotExistsForUsingPOST(authorMapper?: string, name?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateAuthorUsingGET200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createAuthorIfNotExistsForUsingPOST(authorMapper, name, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthorApi.createAuthorIfNotExistsForUsingPOST']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary creates a new author
         * @param {string} [name] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createAuthorUsingGET(name?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateAuthorUsingGET200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createAuthorUsingGET(name, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthorApi.createAuthorUsingGET']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary creates a new author
         * @param {string} [name] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createAuthorUsingPOST(name?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateAuthorUsingGET200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createAuthorUsingPOST(name, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthorApi.createAuthorUsingPOST']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Returns the Author Name of the author
         * @param {string} [authorID] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAuthorNameUsingGET(authorID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetAuthorNameUsingGET200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAuthorNameUsingGET(authorID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthorApi.getAuthorNameUsingGET']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Returns the Author Name of the author
         * @param {string} [authorID] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAuthorNameUsingPOST(authorID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetAuthorNameUsingGET200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAuthorNameUsingPOST(authorID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthorApi.getAuthorNameUsingPOST']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary returns an array of all pads this author contributed to
         * @param {string} [authorID] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listPadsOfAuthorUsingGET(authorID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListPadsUsingGET200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listPadsOfAuthorUsingGET(authorID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthorApi.listPadsOfAuthorUsingGET']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary returns an array of all pads this author contributed to
         * @param {string} [authorID] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listPadsOfAuthorUsingPOST(authorID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListPadsUsingGET200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listPadsOfAuthorUsingPOST(authorID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthorApi.listPadsOfAuthorUsingPOST']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary returns all sessions of an author
         * @param {string} [authorID] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listSessionsOfAuthorUsingGET(authorID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListSessionsOfGroupUsingGET200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listSessionsOfAuthorUsingGET(authorID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthorApi.listSessionsOfAuthorUsingGET']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary returns all sessions of an author
         * @param {string} [authorID] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listSessionsOfAuthorUsingPOST(authorID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListSessionsOfGroupUsingGET200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listSessionsOfAuthorUsingPOST(authorID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthorApi.listSessionsOfAuthorUsingPOST']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthorApi - factory interface
 * @export
 */
export const AuthorApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthorApiFp(configuration)
    return {
        /**
         * 
         * @summary this functions helps you to map your application author ids to Etherpad author ids
         * @param {string} [authorMapper] 
         * @param {string} [name] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAuthorIfNotExistsForUsingGET(authorMapper?: string, name?: string, options?: any): AxiosPromise<CreateAuthorUsingGET200Response> {
            return localVarFp.createAuthorIfNotExistsForUsingGET(authorMapper, name, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary this functions helps you to map your application author ids to Etherpad author ids
         * @param {string} [authorMapper] 
         * @param {string} [name] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAuthorIfNotExistsForUsingPOST(authorMapper?: string, name?: string, options?: any): AxiosPromise<CreateAuthorUsingGET200Response> {
            return localVarFp.createAuthorIfNotExistsForUsingPOST(authorMapper, name, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary creates a new author
         * @param {string} [name] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAuthorUsingGET(name?: string, options?: any): AxiosPromise<CreateAuthorUsingGET200Response> {
            return localVarFp.createAuthorUsingGET(name, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary creates a new author
         * @param {string} [name] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAuthorUsingPOST(name?: string, options?: any): AxiosPromise<CreateAuthorUsingGET200Response> {
            return localVarFp.createAuthorUsingPOST(name, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Returns the Author Name of the author
         * @param {string} [authorID] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAuthorNameUsingGET(authorID?: string, options?: any): AxiosPromise<GetAuthorNameUsingGET200Response> {
            return localVarFp.getAuthorNameUsingGET(authorID, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Returns the Author Name of the author
         * @param {string} [authorID] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAuthorNameUsingPOST(authorID?: string, options?: any): AxiosPromise<GetAuthorNameUsingGET200Response> {
            return localVarFp.getAuthorNameUsingPOST(authorID, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary returns an array of all pads this author contributed to
         * @param {string} [authorID] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPadsOfAuthorUsingGET(authorID?: string, options?: any): AxiosPromise<ListPadsUsingGET200Response> {
            return localVarFp.listPadsOfAuthorUsingGET(authorID, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary returns an array of all pads this author contributed to
         * @param {string} [authorID] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPadsOfAuthorUsingPOST(authorID?: string, options?: any): AxiosPromise<ListPadsUsingGET200Response> {
            return localVarFp.listPadsOfAuthorUsingPOST(authorID, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary returns all sessions of an author
         * @param {string} [authorID] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSessionsOfAuthorUsingGET(authorID?: string, options?: any): AxiosPromise<ListSessionsOfGroupUsingGET200Response> {
            return localVarFp.listSessionsOfAuthorUsingGET(authorID, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary returns all sessions of an author
         * @param {string} [authorID] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSessionsOfAuthorUsingPOST(authorID?: string, options?: any): AxiosPromise<ListSessionsOfGroupUsingGET200Response> {
            return localVarFp.listSessionsOfAuthorUsingPOST(authorID, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthorApi - interface
 * @export
 * @interface AuthorApi
 */
export interface AuthorApiInterface {
    /**
     * 
     * @summary this functions helps you to map your application author ids to Etherpad author ids
     * @param {string} [authorMapper] 
     * @param {string} [name] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthorApiInterface
     */
    createAuthorIfNotExistsForUsingGET(authorMapper?: string, name?: string, options?: RawAxiosRequestConfig): AxiosPromise<CreateAuthorUsingGET200Response>;

    /**
     * 
     * @summary this functions helps you to map your application author ids to Etherpad author ids
     * @param {string} [authorMapper] 
     * @param {string} [name] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthorApiInterface
     */
    createAuthorIfNotExistsForUsingPOST(authorMapper?: string, name?: string, options?: RawAxiosRequestConfig): AxiosPromise<CreateAuthorUsingGET200Response>;

    /**
     * 
     * @summary creates a new author
     * @param {string} [name] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthorApiInterface
     */
    createAuthorUsingGET(name?: string, options?: RawAxiosRequestConfig): AxiosPromise<CreateAuthorUsingGET200Response>;

    /**
     * 
     * @summary creates a new author
     * @param {string} [name] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthorApiInterface
     */
    createAuthorUsingPOST(name?: string, options?: RawAxiosRequestConfig): AxiosPromise<CreateAuthorUsingGET200Response>;

    /**
     * 
     * @summary Returns the Author Name of the author
     * @param {string} [authorID] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthorApiInterface
     */
    getAuthorNameUsingGET(authorID?: string, options?: RawAxiosRequestConfig): AxiosPromise<GetAuthorNameUsingGET200Response>;

    /**
     * 
     * @summary Returns the Author Name of the author
     * @param {string} [authorID] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthorApiInterface
     */
    getAuthorNameUsingPOST(authorID?: string, options?: RawAxiosRequestConfig): AxiosPromise<GetAuthorNameUsingGET200Response>;

    /**
     * 
     * @summary returns an array of all pads this author contributed to
     * @param {string} [authorID] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthorApiInterface
     */
    listPadsOfAuthorUsingGET(authorID?: string, options?: RawAxiosRequestConfig): AxiosPromise<ListPadsUsingGET200Response>;

    /**
     * 
     * @summary returns an array of all pads this author contributed to
     * @param {string} [authorID] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthorApiInterface
     */
    listPadsOfAuthorUsingPOST(authorID?: string, options?: RawAxiosRequestConfig): AxiosPromise<ListPadsUsingGET200Response>;

    /**
     * 
     * @summary returns all sessions of an author
     * @param {string} [authorID] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthorApiInterface
     */
    listSessionsOfAuthorUsingGET(authorID?: string, options?: RawAxiosRequestConfig): AxiosPromise<ListSessionsOfGroupUsingGET200Response>;

    /**
     * 
     * @summary returns all sessions of an author
     * @param {string} [authorID] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthorApiInterface
     */
    listSessionsOfAuthorUsingPOST(authorID?: string, options?: RawAxiosRequestConfig): AxiosPromise<ListSessionsOfGroupUsingGET200Response>;

}

/**
 * AuthorApi - object-oriented interface
 * @export
 * @class AuthorApi
 * @extends {BaseAPI}
 */
export class AuthorApi extends BaseAPI implements AuthorApiInterface {
    /**
     * 
     * @summary this functions helps you to map your application author ids to Etherpad author ids
     * @param {string} [authorMapper] 
     * @param {string} [name] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthorApi
     */
    public createAuthorIfNotExistsForUsingGET(authorMapper?: string, name?: string, options?: RawAxiosRequestConfig) {
        return AuthorApiFp(this.configuration).createAuthorIfNotExistsForUsingGET(authorMapper, name, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary this functions helps you to map your application author ids to Etherpad author ids
     * @param {string} [authorMapper] 
     * @param {string} [name] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthorApi
     */
    public createAuthorIfNotExistsForUsingPOST(authorMapper?: string, name?: string, options?: RawAxiosRequestConfig) {
        return AuthorApiFp(this.configuration).createAuthorIfNotExistsForUsingPOST(authorMapper, name, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary creates a new author
     * @param {string} [name] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthorApi
     */
    public createAuthorUsingGET(name?: string, options?: RawAxiosRequestConfig) {
        return AuthorApiFp(this.configuration).createAuthorUsingGET(name, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary creates a new author
     * @param {string} [name] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthorApi
     */
    public createAuthorUsingPOST(name?: string, options?: RawAxiosRequestConfig) {
        return AuthorApiFp(this.configuration).createAuthorUsingPOST(name, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Returns the Author Name of the author
     * @param {string} [authorID] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthorApi
     */
    public getAuthorNameUsingGET(authorID?: string, options?: RawAxiosRequestConfig) {
        return AuthorApiFp(this.configuration).getAuthorNameUsingGET(authorID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Returns the Author Name of the author
     * @param {string} [authorID] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthorApi
     */
    public getAuthorNameUsingPOST(authorID?: string, options?: RawAxiosRequestConfig) {
        return AuthorApiFp(this.configuration).getAuthorNameUsingPOST(authorID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary returns an array of all pads this author contributed to
     * @param {string} [authorID] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthorApi
     */
    public listPadsOfAuthorUsingGET(authorID?: string, options?: RawAxiosRequestConfig) {
        return AuthorApiFp(this.configuration).listPadsOfAuthorUsingGET(authorID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary returns an array of all pads this author contributed to
     * @param {string} [authorID] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthorApi
     */
    public listPadsOfAuthorUsingPOST(authorID?: string, options?: RawAxiosRequestConfig) {
        return AuthorApiFp(this.configuration).listPadsOfAuthorUsingPOST(authorID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary returns all sessions of an author
     * @param {string} [authorID] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthorApi
     */
    public listSessionsOfAuthorUsingGET(authorID?: string, options?: RawAxiosRequestConfig) {
        return AuthorApiFp(this.configuration).listSessionsOfAuthorUsingGET(authorID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary returns all sessions of an author
     * @param {string} [authorID] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthorApi
     */
    public listSessionsOfAuthorUsingPOST(authorID?: string, options?: RawAxiosRequestConfig) {
        return AuthorApiFp(this.configuration).listSessionsOfAuthorUsingPOST(authorID, options).then((request) => request(this.axios, this.basePath));
    }
}

