export interface RoomConfig {
	FEATURE_ADMINISTRATE_ROOMS_ENABLED: boolean;
	FEATURE_ROOM_COPY_ENABLED: boolean;
	FEATURE_ROOM_LINK_INVITATION_EXTERNAL_PERSONS_ENABLED: boolean;
	FEATURE_ROOM_SHARE: boolean;
}
