export interface RoomConfig {
	FEATURE_ROOMS_ENABLED: boolean;
	FEATURE_ROOM_INVITATION_LINKS_ENABLED: boolean;
	FEATURE_ROOM_COPY_ENABLED: boolean;
	FEATURE_ROOM_SHARE: boolean;
	FEATURE_ADMINISTRATE_ROOMS_ENABLED: boolean;
}
