import { Configuration } from '@hpi-schul-cloud/commons';

const deletionConfig = {
	ADMIN_API__DELETION_DELETE_AFTER_MINUTES: Configuration.get('ADMIN_API__DELETION_DELETE_AFTER_MINUTES') as number,
	ADMIN_API__DELETION_MODIFICATION_THRESHOLD_MS: Configuration.get(
		'ADMIN_API__DELETION_MODIFICATION_THRESHOLD_MS'
	) as number,
	ADMIN_API__DELETION_CONSIDER_FAILED_AFTER_MS: Configuration.get(
		'ADMIN_API__DELETION_CONSIDER_FAILED_AFTER_MS'
	) as number,
	ADMIN_API__DELETION_MAX_CONCURRENT_DELETION_REQUESTS: Configuration.get(
		'ADMIN_API__DELETION_MAX_CONCURRENT_DELETION_REQUESTS'
	) as number,
};

const config = () => deletionConfig;

export const deletionTestConfig = () => {
	const conf = config();
	conf.ADMIN_API__DELETION_DELETE_AFTER_MINUTES = 1;
	conf.ADMIN_API__DELETION_MODIFICATION_THRESHOLD_MS = 100;
	conf.ADMIN_API__DELETION_CONSIDER_FAILED_AFTER_MS = 1000;
	conf.ADMIN_API__DELETION_MAX_CONCURRENT_DELETION_REQUESTS = 2;
	return conf;
};
