export { SchulconnexResponse } from './schulconnex.response';
export { SchulconnexRole } from './schulconnex-role';
export { SchulconnexGroupRole } from './schulconnex-group-role';
export { SchulconnexGroupType } from './schulconnex-group-type';
export { SchulconnexNameResponse } from './schulconnex-name-response';
export { SchulconnexGruppeResponse } from './schulconnex-gruppe-response';
export { SchulconnexGruppenResponse } from './schulconnex-gruppen-response';
export { SchulconnexOrganisationResponse } from './schulconnex-organisation-response';
export { SchulconnexPersonenkontextResponse } from './schulconnex-personenkontext-response';
export { SchulconnexGruppenzugehoerigkeitResponse } from './schulconnex-gruppenzugehoerigkeit-response';
export { SchulconnexPersonResponse } from './schulconnex-person-response';
export { SchulconnexSonstigeGruppenzugehoerigeResponse } from './schulconnex-sonstige-gruppenzugehoerige-response';
export { SchulconnexAnschriftResponse } from './schulconnex-anschrift-response';
export { SchulconnexResponseValidationGroups } from './schulconnex-response-validation-groups';
export { SchulconnexErreichbarkeitenResponse } from './schulconnex-erreichbarkeiten-response';
export { SchulconnexCommunicationType } from './schulconnex-communication-type';
export { SchulconnexLaufzeitResponse, lernperiodeFormat } from './schulconnex-laufzeit-response';
export * from './policies-info';
