export * from './policies-info';
export { SchulconnexAnschriftResponse } from './schulconnex-anschrift.response';
export { SchulconnexCommunicationType } from './schulconnex-communication-type';
export { SchulconnexErreichbarkeitenResponse } from './schulconnex-erreichbarkeiten.response';
export { SchulconnexGroupRole } from './schulconnex-group-role';
export { SchulconnexGroupType } from './schulconnex-group-type';
export { SchulconnexGruppeResponse } from './schulconnex-gruppe.response';
export { SchulconnexGruppenResponse } from './schulconnex-gruppen.response';
export { SchulconnexGruppenzugehoerigkeitResponse } from './schulconnex-gruppenzugehoerigkeit.response';
export { lernperiodeFormat, SchulconnexLaufzeitResponse } from './schulconnex-laufzeit.response';
export { SchulconnexNameResponse } from './schulconnex-name.response';
export { SchulconnexOrganisationResponse } from './schulconnex-organisation.response';
export { SchulconnexPersonResponse } from './schulconnex-person.response';
export { SchulconnexPersonenkontextResponse } from './schulconnex-personenkontext.response';
export { SchulconnexResponseValidationGroups } from './schulconnex-response-validation-groups';
export { SchulconnexRole } from './schulconnex-role';
export { SchulconnexSonstigeGruppenzugehoerigeResponse } from './schulconnex-sonstige-gruppenzugehoerige.response';
export { SchulconnexResponse } from './schulconnex.response';
