export { SchulconnexResponse } from './schulconnex.response';
export { SchulconnexRole } from './schulconnex-role';
export { SchulconnexGroupRole } from './schulconnex-group-role';
export { SchulconnexGroupType } from './schulconnex-group-type';
export { SchulconnexGruppenResponse } from './schulconnex-gruppen-response';
export { SchulconnexPersonenkontextResponse } from './schulconnex-personenkontext-response';
export { SchulconnexSonstigeGruppenzugehoerigeResponse } from './schulconnex-sonstige-gruppenzugehoerige-response';
export { SchulconnexResponseValidationGroups } from './schulconnex-response-validation-groups';
export { SchulconnexErreichbarkeitenResponse } from './schulconnex-erreichbarkeiten-response';
export { SchulconnexCommunicationType } from './schulconnex-communication-type';
export { SchulconnexLaufzeitResponse, lernperiodeFormat } from './schulconnex-laufzeit-response';
export * from './policies-info';
