EXTERNAL_SECRETS_POSTFIX: ""
NOTIFICATION_SERVER_PORT: 3033
NOTIFICATION_SERVER_REPLICAS: 1
NOTIFICATION_SERVER_CPU_LIMITS: "2000m"
NOTIFICATION_SERVER_MEMORY_LIMITS: "2Gi"
NOTIFICATION_SERVER_CPU_REQUESTS: "100m"
NOTIFICATION_SERVER_MEMORY_REQUESTS: "150Mi"
