export enum ErrorType {
	ETHERPAD_SERVER_BAD_REQUEST = 'ETHERPAD_SERVER_BAD_REQUEST',
	ETHERPAD_SERVER_INTERNAL_ERROR = 'ETHERPAD_SERVER_INTERNAL_ERROR',
	ETHERPAD_SERVER_FUNCTION_NOT_FOUND = 'ETHERPAD_SERVER_FUNCTION_NOT_FOUND',
	ETHERPAD_SERVER_WRONG_API_KEY = 'ETHERPAD_SERVER_WRONG_API_KEY',
	ETHERPAD_SERVER_CONNECTION_ERROR = 'ETHERPAD_SERVER_CONNECTION_ERROR',
}
