export enum EtherpadErrorType {
	BAD_REQUEST = 'BAD_REQUEST',
	INTERNAL_ERROR = 'INTERNAL_ERROR',
	FUNCTION_NOT_FOUND = 'FUNCTION_NOT_FOUND',
	WRONG_API_KEY = 'WRONG_API_KEY',
	CONNECTION_ERROR = 'CONNECTION_ERROR',
}
