// All user accounts are organized by school in a single array

import { Role, RoleProperties } from '@shared/domain/entity';
import { Permission, RoleName } from '@shared/domain/interface';
import { roleFactory } from '@shared/testing/factory';
import { DeepPartial } from 'fishery';

type SeedRoleProperties = Omit<RoleProperties, 'roles'> & {
	id: string;
	createdAt: string;
	updatedAt: string;
	roles: RoleName[];
};

const roleSeedData: { [key: string | RoleName]: SeedRoleProperties } = {
	user: {
		id: '0000d186816abba584714c95',
		createdAt: '2017-01-01T00:06:37.148Z',
		updatedAt: '2023-04-04T12:33:09.676Z',
		name: RoleName.USER,
		roles: [],
		permissions: [
			Permission.ACCOUNT_EDIT,
			Permission.BASE_VIEW,
			Permission.CALENDAR_CREATE,
			Permission.CALENDAR_EDIT,
			Permission.CALENDAR_VIEW,
			Permission.CLASS_VIEW,
			Permission.COMMENTS_CREATE,
			Permission.COMMENTS_EDIT,
			Permission.COMMENTS_VIEW,
			Permission.CONTENT_NON_OER_VIEW,
			Permission.CONTENT_VIEW,
			Permission.COURSE_VIEW,
			Permission.COURSEGROUP_CREATE,
			Permission.COURSEGROUP_EDIT,
			Permission.DASHBOARD_VIEW,
			Permission.FEDERALSTATE_VIEW,
			Permission.FILE_CREATE,
			Permission.FILE_DELETE,
			Permission.FILE_MOVE,
			Permission.FILESTORAGE_CREATE,
			Permission.FILESTORAGE_EDIT,
			Permission.FILESTORAGE_REMOVE,
			Permission.FILESTORAGE_VIEW,
			Permission.FOLDER_CREATE,
			Permission.FOLDER_DELETE,
			Permission.HELPDESK_CREATE,
			Permission.HOMEWORK_VIEW,
			Permission.LERNSTORE_VIEW,
			Permission.LINK_CREATE,
			Permission.NEWS_VIEW,
			Permission.NOTIFICATION_CREATE,
			Permission.NOTIFICATION_EDIT,
			Permission.NOTIFICATION_VIEW,
			Permission.PASSWORD_EDIT,
			Permission.PWRECOVERY_CREATE,
			Permission.PWRECOVERY_EDIT,
			Permission.PWRECOVERY_VIEW,
			Permission.RELEASES_VIEW,
			Permission.ROLE_VIEW,
			Permission.SUBMISSIONS_CREATE,
			Permission.SUBMISSIONS_EDIT,
			Permission.SUBMISSIONS_VIEW,
			Permission.TEAM_VIEW,
			Permission.TOOL_VIEW,
			Permission.TOPIC_VIEW,
			Permission.NEXTCLOUD_USER,
			Permission.JOIN_MEETING,
		],
	},
	administrator: {
		id: '0000d186816abba584714c96',
		createdAt: '2017-01-01T00:06:37.148Z',
		updatedAt: '2023-04-03T13:27:56.587Z',
		name: RoleName.ADMINISTRATOR,
		roles: [RoleName.USER],
		permissions: [
			Permission.ACCOUNT_CREATE,
			Permission.ADMIN_VIEW,
			Permission.CLASS_CREATE,
			Permission.CLASS_EDIT,
			Permission.CLASS_FULL_ADMIN,
			Permission.CLASS_LIST,
			Permission.CLASS_REMOVE,
			Permission.COURSE_CREATE,
			Permission.COURSE_EDIT,
			Permission.COURSE_REMOVE,
			Permission.DATASOURCES_CREATE,
			Permission.DATASOURCES_DELETE,
			Permission.DATASOURCES_EDIT,
			Permission.DATASOURCES_RUN,
			Permission.DATASOURCES_RUN_VIEW,
			Permission.DATASOURCES_VIEW,
			Permission.ENTERTHECLOUD_START,
			Permission.HELPDESK_EDIT,
			Permission.HELPDESK_VIEW,
			Permission.SCHOOL_IMPORT_USERS_MIGRATE,
			Permission.SCHOOL_IMPORT_USERS_UPDATE,
			Permission.SCHOOL_IMPORT_USERS_VIEW,
			Permission.NEWS_CREATE,
			Permission.NEWS_EDIT,
			Permission.REQUEST_CONSENTS,
			Permission.SCHOOL_EDIT,
			Permission.SCHOOL_NEWS_EDIT,
			Permission.SCHOOL_CHAT_MANAGE,
			Permission.SCHOOL_LOGO_MANAGE,
			Permission.SCHOOL_STUDENT_TEAM_MANAGE,
			Permission.STUDENT_CREATE,
			Permission.STUDENT_DELETE,
			Permission.STUDENT_EDIT,
			Permission.STUDENT_LIST,
			Permission.STUDENT_SKIP_REGISTRATION,
			Permission.SUBMISSIONS_SCHOOL_VIEW,
			Permission.SYNC_START,
			Permission.TEACHER_CREATE,
			Permission.TEACHER_DELETE,
			Permission.TEACHER_EDIT,
			Permission.TEACHER_LIST,
			Permission.TEACHER_SKIP_REGISTRATION,
			Permission.TEAM_INVITE_EXTERNAL,
			Permission.TEAM_CREATE,
			Permission.TEAM_EDIT,
			Permission.SCHOOL_PERMISSION_VIEW,
			Permission.SCHOOL_PERMISSION_CHANGE,
			Permission.SYSTEM_EDIT,
			Permission.SYSTEM_CREATE,
			Permission.SYSTEM_VIEW,
			Permission.SCHOOL_TOOL_ADMIN,
			Permission.USER_CHANGE_OWN_NAME,
		],
	},
	superhero: {
		id: '0000d186816abba584714c97',
		createdAt: '2017-01-01T00:06:37.148Z',
		updatedAt: '2022-09-22T13:14:23.839Z',
		name: RoleName.SUPERHERO,
		roles: [RoleName.USER],
		permissions: [
			Permission.ACCOUNT_DELETE,
			Permission.ACCOUNT_VIEW,
			Permission.ADMIN_EDIT,
			Permission.CLASS_LIST,
			Permission.CREATE_SUPPORT_JWT,
			Permission.DATASOURCES_CREATE,
			Permission.DATASOURCES_DELETE,
			Permission.DATASOURCES_EDIT,
			Permission.DATASOURCES_RUN,
			Permission.DATASOURCES_RUN_VIEW,
			Permission.DATASOURCES_VIEW,
			Permission.FEDERALSTATE_CREATE,
			Permission.FEDERALSTATE_EDIT,
			Permission.OAUTH_CLIENT_EDIT,
			Permission.OAUTH_CLIENT_VIEW,
			Permission.RELEASES_CREATE,
			Permission.RELEASES_EDIT,
			Permission.REQUEST_CONSENTS,
			Permission.ROLE_CREATE,
			Permission.ROLE_EDIT,
			Permission.SCHOOL_CREATE,
			Permission.SCHOOL_EDIT,
			Permission.STUDENT_CREATE,
			Permission.STUDENT_DELETE,
			Permission.STUDENT_EDIT,
			Permission.STUDENT_LIST,
			Permission.SUBMISSIONS_SCHOOL_VIEW,
			Permission.SYNC_START,
			Permission.TOOL_ADMIN,
			Permission.TEACHER_CREATE,
			Permission.TEACHER_DELETE,
			Permission.TEACHER_EDIT,
			Permission.TEACHER_LIST,
			Permission.TEAM_CREATE,
			Permission.TEAM_EDIT,
			Permission.TOOL_CREATE,
			Permission.TOOL_EDIT,
			Permission.USER_CHANGE_OWN_NAME,
			Permission.YEARS_EDIT,
		],
	},
	teacher: {
		id: '0000d186816abba584714c98',
		createdAt: '2017-01-01T00:06:37.148Z',
		updatedAt: '2023-04-28T13:00:08.424Z',
		name: RoleName.TEACHER,
		roles: [RoleName.USER],
		permissions: [
			Permission.ACCOUNT_CREATE,
			Permission.CLASS_CREATE,
			Permission.CLASS_EDIT,
			Permission.CLASS_LIST,
			Permission.CLASS_REMOVE,
			Permission.COURSE_CREATE,
			Permission.COURSE_EDIT,
			Permission.COURSE_REMOVE,
			Permission.ENTERTHECLOUD_START,
			Permission.LESSONS_VIEW,
			Permission.NEWS_CREATE,
			Permission.NEWS_EDIT,
			Permission.REQUEST_CONSENTS,
			Permission.SCHOOL_NEWS_EDIT,
			Permission.STUDENT_EDIT,
			Permission.STUDENT_LIST,
			Permission.STUDENT_SKIP_REGISTRATION,
			Permission.SUBMISSIONS_SCHOOL_VIEW,
			Permission.TEACHER_LIST,
			Permission.TEAM_INVITE_EXTERNAL,
			Permission.TEAM_INVITE_EXTERNAL,
			Permission.TOOL_CREATE,
			Permission.TOOL_EDIT,
			Permission.TOOL_NEW_VIEW,
			Permission.TOPIC_CREATE,
			Permission.TOPIC_EDIT,
			Permission.USERGROUP_CREATE,
			Permission.USERGROUP_EDIT,
			Permission.USER_CHANGE_OWN_NAME,
			Permission.USER_CREATE,
			Permission.TASK_DASHBOARD_TEACHER_VIEW_V3,
			Permission.TEAM_CREATE,
			Permission.TEAM_EDIT,
			Permission.START_MEETING,
			Permission.HOMEWORK_CREATE,
			Permission.HOMEWORK_EDIT,
			Permission.CONTEXT_TOOL_ADMIN,
		],
	},
	student: {
		id: '0000d186816abba584714c99',
		createdAt: '2017-01-01T00:06:37.148Z',
		updatedAt: '2023-02-14T08:59:35.396Z',
		name: RoleName.STUDENT,
		roles: [RoleName.USER],
		permissions: [
			Permission.TASK_DASHBOARD_VIEW_V3,
			Permission.JOIN_MEETING,
			Permission.TEAM_CREATE,
			Permission.TEAM_EDIT,
			Permission.TOOL_CREATE_ETHERPAD,
		],
	},
	helpdesk: {
		id: '0000d186816abba584714d01',
		createdAt: '2017-01-01T00:06:37.148Z',
		updatedAt: '2022-05-20T13:33:18.077Z',
		name: RoleName.HELPDESK,
		roles: [RoleName.USER],
		permissions: [Permission.HELPDESK_EDIT, Permission.HELPDESK_VIEW],
	},
	teammember: {
		id: '5bb5c190fb457b1c3c0c7e0f',
		createdAt: '2017-01-01T00:06:37.148Z',
		updatedAt: '2023-05-05T07:39:11.036Z',
		name: RoleName.TEAMMEMBER,
		roles: [],
		permissions: [
			Permission.NEWS_VIEW,
			Permission.UPLOAD_FILES,
			Permission.USE_LIBREOFFICE,
			Permission.USE_ROCKETCHAT,
			Permission.JOIN_MEETING,
		],
	},
	teamexpert: {
		id: '5bb5c391fb457b1c3c0c7e10',
		createdAt: '2017-01-01T00:06:37.148Z',
		updatedAt: '2023-05-05T07:39:11.040Z',
		name: RoleName.TEAMEXPERT,
		roles: [],
		permissions: [
			Permission.CALENDAR_VIEW,
			Permission.NEWS_VIEW,
			Permission.UPLOAD_FILES,
			Permission.USE_LIBREOFFICE,
			Permission.USE_ROCKETCHAT,
			Permission.JOIN_MEETING,
		],
	},
	teamleader: {
		id: '5bb5c49efb457b1c3c0c7e11',
		createdAt: '2017-01-01T00:06:37.148Z',
		updatedAt: '2022-05-20T13:33:18.077Z',
		name: RoleName.TEAMLEADER,
		roles: [RoleName.TEAMMEMBER],
		permissions: [
			Permission.ADD_SCHOOL_MEMBERS,
			Permission.CALENDAR_CREATE,
			Permission.CALENDAR_EDIT,
			Permission.CHANGE_TEAM_ROLES,
			Permission.CREATE_TOPICS_AND_TASKS,
			Permission.EDIT_ALL_FILES,
			Permission.NEWS_CREATE,
			Permission.START_MEETING,
			Permission.JOIN_MEETING,
		],
	},
	teamadministrator: {
		id: '5bb5c545fb457b1c3c0c7e13',
		createdAt: '2017-01-01T00:06:37.148Z',
		updatedAt: '2023-05-05T07:39:11.028Z',
		name: RoleName.TEAMADMINISTRATOR,
		roles: [RoleName.TEAMLEADER],
		permissions: [
			Permission.DEFAULT_FILE_PERMISSIONS,
			Permission.INVITE_ADMINISTRATORS,
			Permission.INVITE_EXPERTS,
			Permission.NEWS_EDIT,
			Permission.REMOVE_MEMBERS,
			Permission.RENAME_TEAM,
			Permission.LEAVE_TEAM,
		],
	},
	teamowner: {
		id: '5bb5c62bfb457b1c3c0c7e14',
		createdAt: '2017-01-01T00:06:37.148Z',
		updatedAt: '2022-05-20T13:33:18.077Z',
		name: RoleName.TEAMOWNER,
		roles: [RoleName.TEAMADMINISTRATOR],
		permissions: [Permission.DELETE_TEAM],
	},
	courseStudent: {
		id: '5bb5c62bfb457b1c3c0c7f00',
		createdAt: '2019-09-09T12:00:00Z',
		updatedAt: '2023-03-01T10:54:36.810Z',
		name: RoleName.COURSESTUDENT,
		roles: [],
		permissions: [
			Permission.COURSE_VIEW,
			Permission.TOOL_VIEW,
			Permission.NEWS_VIEW,
			Permission.ROLE_VIEW,
			Permission.USERGROUP_VIEW,
			Permission.COURSEGROUP_CREATE,
			Permission.COURSEGROUP_EDIT,
			Permission.LESSONS_VIEW,
			Permission.HOMEWORK_VIEW,
			Permission.COMMENTS_VIEW,
			Permission.COMMENTS_CREATE,
			Permission.COMMENTS_EDIT,
			Permission.SUBMISSIONS_VIEW,
			Permission.SUBMISSIONS_CREATE,
			Permission.SUBMISSIONS_EDIT,
			Permission.FILESTORAGE_VIEW,
			Permission.FILESTORAGE_EDIT,
			Permission.FILESTORAGE_CREATE,
			Permission.FILESTORAGE_REMOVE,
			Permission.CONTENT_VIEW,
			Permission.CONTENT_NON_OER_VIEW,
			Permission.JOIN_MEETING,
		],
	},
	courseTeacher: {
		id: '5bb5c62bfb457b1c3c0c7f01',
		createdAt: '2019-09-09T12:00:00Z',
		updatedAt: '2022-05-20T13:33:18.077Z',
		name: RoleName.COURSETEACHER,
		roles: [RoleName.COURSESTUDENT],
		permissions: [
			Permission.COURSE_CREATE,
			Permission.COURSE_EDIT,
			Permission.COURSE_DELETE,
			Permission.HOMEWORK_CREATE,
			Permission.HOMEWORK_EDIT,
			Permission.LESSONS_CREATE,
			Permission.NEWS_CREATE,
			Permission.NEWS_EDIT,
			Permission.TOOL_CREATE,
			Permission.TOOL_EDIT,
			Permission.TOOL_NEW_VIEW,
			Permission.TOPIC_CREATE,
			Permission.TOPIC_EDIT,
			Permission.USER_CREATE,
			Permission.USERGROUP_CREATE,
			Permission.USERGROUP_EDIT,
			Permission.SCOPE_PERMISSIONS_VIEW,
			Permission.START_MEETING,
		],
	},
	courseSubstitutionTeacher: {
		id: '5bb5c62bfb457b1c3c0c7f02',
		createdAt: '2019-09-09T12:00:00Z',
		updatedAt: '2022-05-20T13:33:18.077Z',
		name: RoleName.COURSESUBSTITUTIONTEACHER,
		roles: [RoleName.COURSESTUDENT],
		permissions: [
			Permission.HOMEWORK_CREATE,
			Permission.HOMEWORK_EDIT,
			Permission.LESSONS_CREATE,
			Permission.NEWS_CREATE,
			Permission.NEWS_EDIT,
			Permission.TOOL_CREATE,
			Permission.TOOL_EDIT,
			Permission.TOOL_NEW_VIEW,
			Permission.TOPIC_CREATE,
			Permission.TOPIC_EDIT,
			Permission.USER_CREATE,
			Permission.USERGROUP_CREATE,
			Permission.USERGROUP_EDIT,
			Permission.SCOPE_PERMISSIONS_VIEW,
			Permission.START_MEETING,
		],
	},
	courseAdministrator: {
		id: '5bb5c62bfb457b1c3c0c7f03',
		createdAt: '2019-09-09T12:00:00Z',
		updatedAt: '2022-05-20T13:33:18.077Z',
		name: RoleName.COURSEADMINISTRATOR,
		roles: [RoleName.COURSETEACHER],
		permissions: [],
	},
	expert: {
		id: '5bd0066a90a9ee0cb4947a9c',
		createdAt: '2017-01-01T00:06:37.148Z',
		updatedAt: '2022-05-20T13:33:18.077Z',
		name: RoleName.EXPERT,
		roles: [RoleName.USER],
		permissions: [],
	},
};
export const roleOrder = [
	'user',
	'administrator',
	'superhero',
	'teacher',
	'student',
	'helpdesk',
	'teammember',
	'teamexpert',
	'teamleader',
	'teamadministrator',
	'teamowner',
	'courseStudent',
	'courseTeacher',
	'courseSubstitutionTeacher',
	'courseAdministrator',
	'expert',
];

export function generateRole(localRoleSeedData?: { [key: string | RoleName]: SeedRoleProperties }) {
	// cache the results for later use
	const rolesByName = {} as Record<RoleName, Role>;

	// create the roles in order
	return roleOrder.map((roleName) => {
		const partial = (localRoleSeedData ?? roleSeedData)[roleName];
		if (!partial) {
			throw new Error(`Role ${roleName} not found`);
		}
		const subRoles = partial.roles.map((rName) => rolesByName[rName]);
		if (subRoles.some((r) => !r)) {
			throw new Error(`Role ${roleName} depends on non existing role`);
		}
		const params: DeepPartial<RoleProperties> = {
			name: partial.name,
			permissions: partial.permissions,
			roles: subRoles,
		};
		const role = roleFactory.buildWithId(params, partial.id);
		if (partial.createdAt) {
			role.createdAt = new Date(partial.createdAt);
		}
		if (partial.updatedAt) {
			role.updatedAt = new Date(partial.updatedAt);
		}

		rolesByName[roleName] = role;
		return role;
	});
}
