export enum RoomInvitationLinkValidationError {
	EXPIRED = 'EXPIRED',
	ONLY_FOR_TEACHERS = 'ONLY_FOR_TEACHERS',
	RESTRICTED_TO_CREATOR_SCHOOL = 'RESTRICTED_TO_CREATOR_SCHOOL',
	CANT_INVITE_STUDENTS_FROM_OTHER_SCHOOL = 'CANT_INVITE_STUDENTS_FROM_OTHER_SCHOOL',
	INVALID_LINK = 'INVALID_LINK',
}
