export enum RoomInvitationLinkValidationError {
	EXPIRED = 'EXPIRED',
	NOT_USABLE_FOR_CURRENT_ROLE = 'NOT_USABLE_FOR_CURRENT_ROLE',
	RESTRICTED_TO_CREATOR_SCHOOL = 'RESTRICTED_TO_CREATOR_SCHOOL',
	CANT_INVITE_STUDENTS_FROM_OTHER_SCHOOL = 'CANT_INVITE_STUDENTS_FROM_OTHER_SCHOOL',
	INVALID_LINK = 'INVALID_LINK',
	ROOM_APPLICANT_WAITING = 'ROOM_APPLICANT_WAITING',
}
