import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import type { ServerConfig } from '../..';

export class ConfigResponse {
	@ApiProperty()
	FEATURE_NEW_SCHOOL_ADMINISTRATION_PAGE_AS_DEFAULT_ENABLED: boolean;

	@ApiProperty()
	MIGRATION_END_GRACE_PERIOD_MS: number;

	@ApiProperty()
	FEATURE_CTL_TOOLS_TAB_ENABLED: boolean;

	@ApiProperty()
	FEATURE_LTI_TOOLS_TAB_ENABLED: boolean;

	@ApiProperty()
	FILES_STORAGE__MAX_FILE_SIZE: number;

	@ApiProperty()
	FEATURE_SHOW_OUTDATED_USERS: boolean;

	@ApiProperty()
	FEATURE_ENABLE_LDAP_SYNC_DURING_MIGRATION: boolean;

	@ApiProperty()
	FEATURE_CTL_CONTEXT_CONFIGURATION_ENABLED: boolean;

	@ApiProperty()
	FEATURE_SHOW_NEW_CLASS_VIEW_ENABLED: boolean;

	@ApiProperty()
	FEATURE_CTL_TOOLS_COPY_ENABLED: boolean;

	@ApiProperty()
	FEATURE_SHOW_MIGRATION_WIZARD: boolean;

	@ApiPropertyOptional()
	MIGRATION_WIZARD_DOCUMENTATION_LINK?: string;

	@ApiProperty()
	FEATURE_TLDRAW_ENABLED: boolean;

	@ApiProperty()
	TLDRAW__ASSETS_ENABLED: boolean;

	@ApiProperty()
	TLDRAW__ASSETS_MAX_SIZE: number;

	@ApiPropertyOptional()
	TLDRAW__ASSETS_ALLOWED_EXTENSIONS_LIST?: string | undefined;

	constructor(config: ServerConfig) {
		this.FEATURE_NEW_SCHOOL_ADMINISTRATION_PAGE_AS_DEFAULT_ENABLED =
			config.FEATURE_NEW_SCHOOL_ADMINISTRATION_PAGE_AS_DEFAULT_ENABLED;
		this.MIGRATION_END_GRACE_PERIOD_MS = config.MIGRATION_END_GRACE_PERIOD_MS;
		this.FEATURE_CTL_TOOLS_TAB_ENABLED = config.ctlToolsTabEnabled;
		this.FEATURE_LTI_TOOLS_TAB_ENABLED = config.ltiToolsTabEnabled;
		this.FILES_STORAGE__MAX_FILE_SIZE = config.FILES_STORAGE__MAX_FILE_SIZE;
		this.FEATURE_SHOW_OUTDATED_USERS = config.FEATURE_SHOW_OUTDATED_USERS;
		this.FEATURE_ENABLE_LDAP_SYNC_DURING_MIGRATION = config.FEATURE_ENABLE_LDAP_SYNC_DURING_MIGRATION;
		this.FEATURE_CTL_CONTEXT_CONFIGURATION_ENABLED = config.contextConfigurationEnabled;
		this.FEATURE_SHOW_NEW_CLASS_VIEW_ENABLED = config.FEATURE_SHOW_NEW_CLASS_VIEW_ENABLED;
		this.FEATURE_CTL_TOOLS_COPY_ENABLED = config.ctlToolsCopyEnabled;
		this.FEATURE_SHOW_MIGRATION_WIZARD = config.FEATURE_SHOW_MIGRATION_WIZARD;
		this.MIGRATION_WIZARD_DOCUMENTATION_LINK = config.MIGRATION_WIZARD_DOCUMENTATION_LINK;
		this.FEATURE_TLDRAW_ENABLED = config.FEATURE_TLDRAW_ENABLED;
		this.TLDRAW__ASSETS_ENABLED = config.TLDRAW__ASSETS_ENABLED;
		this.TLDRAW__ASSETS_MAX_SIZE = config.TLDRAW__ASSETS_MAX_SIZE;
		this.TLDRAW__ASSETS_ALLOWED_EXTENSIONS_LIST = config.TLDRAW__ASSETS_ALLOWED_EXTENSIONS_LIST;
	}
}

/**
 TODO missed keys - check type from default.schema.json

 	'ADMIN_TABLES_DISPLAY_CONSENT_COLUMN',
	'ALERT_STATUS_URL',
	'FEATURE_ES_COLLECTIONS_ENABLED',
	'FEATURE_EXTENSIONS_ENABLED',
	'FEATURE_TEAMS_ENABLED',
	'FEATURE_LERNSTORE_ENABLED',
	'FEATURE_ADMIN_TOGGLE_STUDENT_LERNSTORE_VIEW_ENABLED',
	'TEACHER_STUDENT_VISIBILITY__IS_CONFIGURABLE',
	'TEACHER_STUDENT_VISIBILITY__IS_ENABLED_BY_DEFAULT',
	'TEACHER_STUDENT_VISIBILITY__IS_VISIBLE',
	'FEATURE_SCHOOL_POLICY_ENABLED_NEW',
	'FEATURE_SCHOOL_TERMS_OF_USE_ENABLED',
	'FEATURE_NEXBOARD_COPY_ENABLED',
	'FEATURE_VIDEOCONFERENCE_ENABLED',
	'ROCKETCHAT_SERVICE_ENABLED',
	'LERNSTORE_MODE',
	'I18N__AVAILABLE_LANGUAGES',
	'I18N__DEFAULT_LANGUAGE',
	'I18N__DEFAULT_TIMEZONE',
	'I18N__FALLBACK_LANGUAGE',
	'JWT_SHOW_TIMEOUT_WARNING_SECONDS',
	'JWT_TIMEOUT_SECONDS',
	'NOT_AUTHENTICATED_REDIRECT_URL',
	'DOCUMENT_BASE_DIR',
	'SC_THEME',
	'SC_TITLE',
	'FEATURE_COLUMN_BOARD_ENABLED',
	'FEATURE_COLUMN_BOARD_SUBMISSIONS_ENABLED',
	'FEATURE_COLUMN_BOARD_LINK_ELEMENT_ENABLED',
	'FEATURE_COLUMN_BOARD_EXTERNAL_TOOLS_ENABLED',
	'FEATURE_COURSE_SHARE',
	'FEATURE_COURSE_SHARE_NEW',
	'FEATURE_LOGIN_LINK_ENABLED',
	'FEATURE_LESSON_SHARE',
	'FEATURE_TASK_SHARE',
	'FEATURE_USER_MIGRATION_ENABLED',
	'FEATURE_COPY_SERVICE_ENABLED',
	'ACCESSIBILITY_REPORT_EMAIL',
	'GHOST_BASE_URL',
	'FEATURE_CONSENT_NECESSARY',
	'FEATURE_IMSCC_COURSE_EXPORT_ENABLED',
	'FEATURE_SCHOOL_SANIS_USER_MIGRATION_ENABLED',
	'FEATURE_ALLOW_INSECURE_LDAP_URL_ENABLED',
 */
