import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { LanguageType } from '@shared/domain/interface';
import { SchulcloudTheme } from '@shared/domain/types';
import type { ServerConfig } from '../..';
import { Timezone } from '../../types/timezone.enum';

export class ConfigResponse {
	@ApiProperty()
	ACCESSIBILITY_REPORT_EMAIL: string;

	@ApiProperty()
	FEATURE_NEW_SCHOOL_ADMINISTRATION_PAGE_AS_DEFAULT_ENABLED: boolean;

	@ApiProperty()
	MIGRATION_END_GRACE_PERIOD_MS: number;

	@ApiProperty()
	FEATURE_CTL_TOOLS_TAB_ENABLED: boolean;

	@ApiProperty()
	FEATURE_LTI_TOOLS_TAB_ENABLED: boolean;

	@ApiProperty()
	FEATURE_SHOW_OUTDATED_USERS: boolean;

	@ApiProperty()
	FEATURE_ENABLE_LDAP_SYNC_DURING_MIGRATION: boolean;

	@ApiProperty()
	CTL_TOOLS_RELOAD_TIME_MS: number;

	@ApiProperty()
	FEATURE_SHOW_NEW_CLASS_VIEW_ENABLED: boolean;

	@ApiProperty()
	FEATURE_CTL_TOOLS_COPY_ENABLED: boolean;

	@ApiProperty()
	FEATURE_SHOW_MIGRATION_WIZARD: boolean;

	@ApiPropertyOptional()
	MIGRATION_WIZARD_DOCUMENTATION_LINK?: string;

	@ApiProperty()
	FEATURE_TLDRAW_ENABLED: boolean;

	@ApiProperty()
	TLDRAW__ASSETS_ENABLED: boolean;

	@ApiProperty()
	TLDRAW__ASSETS_MAX_SIZE: number;

	@ApiProperty()
	TLDRAW__ASSETS_ALLOWED_MIME_TYPES_LIST: string[];

	@ApiProperty()
	ADMIN_TABLES_DISPLAY_CONSENT_COLUMN: boolean;

	@ApiProperty({ type: String, nullable: true })
	ALERT_STATUS_URL: string | null;

	@ApiProperty()
	FEATURE_ES_COLLECTIONS_ENABLED: boolean;

	@ApiProperty()
	FEATURE_EXTENSIONS_ENABLED: boolean;

	@ApiProperty()
	FEATURE_TEAMS_ENABLED: boolean;

	@ApiProperty()
	FEATURE_LERNSTORE_ENABLED: boolean;

	@ApiProperty()
	FEATURE_ADMIN_TOGGLE_STUDENT_LERNSTORE_VIEW_ENABLED: boolean;

	@ApiProperty()
	TEACHER_STUDENT_VISIBILITY__IS_CONFIGURABLE: boolean;

	@ApiProperty()
	TEACHER_STUDENT_VISIBILITY__IS_ENABLED_BY_DEFAULT: boolean;

	@ApiProperty()
	TEACHER_STUDENT_VISIBILITY__IS_VISIBLE: boolean;

	@ApiProperty()
	FEATURE_SCHOOL_POLICY_ENABLED_NEW: boolean;

	@ApiProperty()
	FEATURE_SCHOOL_TERMS_OF_USE_ENABLED: boolean;

	@ApiProperty()
	FEATURE_NEXBOARD_COPY_ENABLED: boolean;

	@ApiProperty()
	FEATURE_VIDEOCONFERENCE_ENABLED: boolean;

	@ApiProperty()
	FEATURE_COLUMN_BOARD_ENABLED: boolean;

	@ApiProperty()
	FEATURE_COLUMN_BOARD_SUBMISSIONS_ENABLED: boolean;

	@ApiProperty()
	FEATURE_COLUMN_BOARD_COLLABORATIVE_TEXT_EDITOR_ENABLED: boolean;

	@ApiProperty()
	FEATURE_COLUMN_BOARD_LINK_ELEMENT_ENABLED: boolean;

	@ApiProperty()
	FEATURE_COLUMN_BOARD_EXTERNAL_TOOLS_ENABLED: boolean;

	@ApiProperty()
	FEATURE_COLUMN_BOARD_SHARE: boolean;

	@ApiProperty()
	FEATURE_COLUMN_BOARD_SOCKET_ENABLED: boolean;

	@ApiProperty()
	FEATURE_COURSE_SHARE: boolean;

	@ApiProperty()
	FEATURE_LOGIN_LINK_ENABLED: boolean;

	@ApiProperty()
	FEATURE_LESSON_SHARE: boolean;

	@ApiProperty()
	FEATURE_TASK_SHARE: boolean;

	@ApiProperty()
	FEATURE_BOARD_LAYOUT_ENABLED: boolean;

	@ApiProperty()
	FEATURE_USER_MIGRATION_ENABLED: boolean;

	@ApiProperty()
	FEATURE_COPY_SERVICE_ENABLED: boolean;

	@ApiProperty()
	FEATURE_CONSENT_NECESSARY: boolean;

	@ApiProperty()
	FEATURE_COMMON_CARTRIDGE_COURSE_EXPORT_ENABLED: boolean;

	@ApiProperty()
	FEATURE_COMMON_CARTRIDGE_COURSE_IMPORT_ENABLED: boolean;

	@ApiProperty()
	FEATURE_SCHOOL_SANIS_USER_MIGRATION_ENABLED: boolean;

	@ApiProperty()
	FEATURE_SCHULCONNEX_COURSE_SYNC_ENABLED: boolean;

	@ApiProperty()
	FEATURE_ALLOW_INSECURE_LDAP_URL_ENABLED: boolean;

	@ApiProperty()
	GHOST_BASE_URL: string;

	@ApiProperty()
	ROCKETCHAT_SERVICE_ENABLED: boolean;

	// LERNSTORE_MODE: boolean; looks like not in use anymore

	@ApiProperty({
		isArray: true,
		enum: LanguageType,
		enumName: 'LanguageType',
	})
	I18N__AVAILABLE_LANGUAGES: LanguageType[];

	@ApiProperty({
		enum: LanguageType,
		enumName: 'LanguageType',
	})
	I18N__DEFAULT_LANGUAGE: LanguageType;

	@ApiProperty({
		enum: LanguageType,
		enumName: 'LanguageType',
	})
	I18N__FALLBACK_LANGUAGE: LanguageType;

	@ApiProperty({ enum: Timezone, enumName: 'Timezone' })
	I18N__DEFAULT_TIMEZONE: Timezone;

	@ApiProperty()
	JWT_SHOW_TIMEOUT_WARNING_SECONDS: number;

	@ApiProperty()
	JWT_TIMEOUT_SECONDS: number;

	@ApiProperty()
	NOT_AUTHENTICATED_REDIRECT_URL: string;

	@ApiProperty()
	DOCUMENT_BASE_DIR: string;

	@ApiProperty({ enum: SchulcloudTheme, enumName: 'SchulcloudTheme' })
	SC_THEME: SchulcloudTheme;

	@ApiProperty()
	SC_TITLE: string;

	@ApiProperty()
	FEATURE_MEDIA_SHELF_ENABLED: boolean;

	@ApiProperty()
	FEATURE_NEW_LAYOUT_ENABLED: boolean;

	constructor(config: ServerConfig) {
		this.ACCESSIBILITY_REPORT_EMAIL = config.ACCESSIBILITY_REPORT_EMAIL;
		this.ADMIN_TABLES_DISPLAY_CONSENT_COLUMN = config.ADMIN_TABLES_DISPLAY_CONSENT_COLUMN;
		this.ALERT_STATUS_URL = config.ALERT_STATUS_URL;
		this.FEATURE_ES_COLLECTIONS_ENABLED = config.FEATURE_ES_COLLECTIONS_ENABLED;
		this.FEATURE_EXTENSIONS_ENABLED = config.FEATURE_EXTENSIONS_ENABLED;
		this.FEATURE_TEAMS_ENABLED = config.FEATURE_TEAMS_ENABLED;
		this.FEATURE_LERNSTORE_ENABLED = config.FEATURE_LERNSTORE_ENABLED;
		this.FEATURE_ADMIN_TOGGLE_STUDENT_LERNSTORE_VIEW_ENABLED =
			config.FEATURE_ADMIN_TOGGLE_STUDENT_LERNSTORE_VIEW_ENABLED;
		this.TEACHER_STUDENT_VISIBILITY__IS_CONFIGURABLE = config.TEACHER_STUDENT_VISIBILITY__IS_CONFIGURABLE;
		this.TEACHER_STUDENT_VISIBILITY__IS_ENABLED_BY_DEFAULT = config.TEACHER_STUDENT_VISIBILITY__IS_ENABLED_BY_DEFAULT;
		this.TEACHER_STUDENT_VISIBILITY__IS_VISIBLE = config.TEACHER_STUDENT_VISIBILITY__IS_VISIBLE;
		this.FEATURE_SCHOOL_POLICY_ENABLED_NEW = config.FEATURE_SCHOOL_POLICY_ENABLED_NEW;
		this.FEATURE_SCHOOL_TERMS_OF_USE_ENABLED = config.FEATURE_SCHOOL_TERMS_OF_USE_ENABLED;
		this.FEATURE_NEXBOARD_COPY_ENABLED = config.FEATURE_NEXBOARD_COPY_ENABLED;
		this.FEATURE_COLUMN_BOARD_ENABLED = config.FEATURE_COLUMN_BOARD_ENABLED;
		this.FEATURE_COLUMN_BOARD_SUBMISSIONS_ENABLED = config.FEATURE_COLUMN_BOARD_SUBMISSIONS_ENABLED;
		this.FEATURE_COLUMN_BOARD_COLLABORATIVE_TEXT_EDITOR_ENABLED =
			config.FEATURE_COLUMN_BOARD_COLLABORATIVE_TEXT_EDITOR_ENABLED;
		this.FEATURE_COLUMN_BOARD_LINK_ELEMENT_ENABLED = config.FEATURE_COLUMN_BOARD_LINK_ELEMENT_ENABLED;
		this.FEATURE_COLUMN_BOARD_EXTERNAL_TOOLS_ENABLED = config.FEATURE_COLUMN_BOARD_EXTERNAL_TOOLS_ENABLED;
		this.FEATURE_COLUMN_BOARD_SHARE = config.FEATURE_COLUMN_BOARD_SHARE;
		this.FEATURE_COLUMN_BOARD_SOCKET_ENABLED = config.FEATURE_COLUMN_BOARD_SOCKET_ENABLED;
		this.FEATURE_COURSE_SHARE = config.FEATURE_COURSE_SHARE;
		this.FEATURE_LOGIN_LINK_ENABLED = config.FEATURE_LOGIN_LINK_ENABLED;
		this.FEATURE_LESSON_SHARE = config.FEATURE_LESSON_SHARE;
		this.FEATURE_TASK_SHARE = config.FEATURE_TASK_SHARE;
		this.FEATURE_BOARD_LAYOUT_ENABLED = config.FEATURE_BOARD_LAYOUT_ENABLED;
		this.FEATURE_USER_MIGRATION_ENABLED = config.userMigrationEnabled;
		this.FEATURE_COPY_SERVICE_ENABLED = config.FEATURE_COPY_SERVICE_ENABLED;
		this.FEATURE_CONSENT_NECESSARY = config.FEATURE_CONSENT_NECESSARY;
		this.FEATURE_COMMON_CARTRIDGE_COURSE_EXPORT_ENABLED = config.FEATURE_COMMON_CARTRIDGE_COURSE_EXPORT_ENABLED;
		this.FEATURE_COMMON_CARTRIDGE_COURSE_IMPORT_ENABLED = config.FEATURE_COMMON_CARTRIDGE_COURSE_IMPORT_ENABLED;
		this.FEATURE_SCHOOL_SANIS_USER_MIGRATION_ENABLED = config.FEATURE_SCHOOL_SANIS_USER_MIGRATION_ENABLED;
		this.FEATURE_ALLOW_INSECURE_LDAP_URL_ENABLED = config.FEATURE_ALLOW_INSECURE_LDAP_URL_ENABLED;
		this.GHOST_BASE_URL = config.GHOST_BASE_URL;
		this.ROCKETCHAT_SERVICE_ENABLED = config.ROCKETCHAT_SERVICE_ENABLED;
		this.I18N__AVAILABLE_LANGUAGES = config.I18N__AVAILABLE_LANGUAGES;
		this.I18N__DEFAULT_LANGUAGE = config.I18N__DEFAULT_LANGUAGE;
		this.I18N__FALLBACK_LANGUAGE = config.I18N__FALLBACK_LANGUAGE;
		this.I18N__DEFAULT_TIMEZONE = config.I18N__DEFAULT_TIMEZONE;
		this.JWT_SHOW_TIMEOUT_WARNING_SECONDS = config.JWT_SHOW_TIMEOUT_WARNING_SECONDS;
		this.JWT_TIMEOUT_SECONDS = config.JWT_TIMEOUT_SECONDS;
		this.NOT_AUTHENTICATED_REDIRECT_URL = config.NOT_AUTHENTICATED_REDIRECT_URL;
		this.DOCUMENT_BASE_DIR = config.DOCUMENT_BASE_DIR;
		this.SC_THEME = config.SC_THEME;
		this.SC_TITLE = config.SC_TITLE;
		this.FEATURE_NEW_SCHOOL_ADMINISTRATION_PAGE_AS_DEFAULT_ENABLED =
			config.FEATURE_NEW_SCHOOL_ADMINISTRATION_PAGE_AS_DEFAULT_ENABLED;
		this.MIGRATION_END_GRACE_PERIOD_MS = config.MIGRATION_END_GRACE_PERIOD_MS;
		this.FEATURE_CTL_TOOLS_TAB_ENABLED = config.ctlToolsTabEnabled;
		this.FEATURE_LTI_TOOLS_TAB_ENABLED = config.ltiToolsTabEnabled;
		this.FEATURE_SHOW_OUTDATED_USERS = config.FEATURE_SHOW_OUTDATED_USERS;
		this.FEATURE_ENABLE_LDAP_SYNC_DURING_MIGRATION = config.FEATURE_ENABLE_LDAP_SYNC_DURING_MIGRATION;
		this.CTL_TOOLS_RELOAD_TIME_MS = config.ctlToolsReloadTimeMs;
		this.FEATURE_SHOW_NEW_CLASS_VIEW_ENABLED = config.FEATURE_SHOW_NEW_CLASS_VIEW_ENABLED;
		this.FEATURE_CTL_TOOLS_COPY_ENABLED = config.ctlToolsCopyEnabled;
		this.FEATURE_SHOW_MIGRATION_WIZARD = config.FEATURE_SHOW_MIGRATION_WIZARD;
		this.MIGRATION_WIZARD_DOCUMENTATION_LINK = config.MIGRATION_WIZARD_DOCUMENTATION_LINK;
		this.FEATURE_TLDRAW_ENABLED = config.FEATURE_TLDRAW_ENABLED;
		this.TLDRAW__ASSETS_ENABLED = config.TLDRAW__ASSETS_ENABLED;
		this.TLDRAW__ASSETS_MAX_SIZE = config.TLDRAW__ASSETS_MAX_SIZE;
		this.TLDRAW__ASSETS_ALLOWED_MIME_TYPES_LIST = config.TLDRAW__ASSETS_ALLOWED_MIME_TYPES_LIST;
		this.FEATURE_VIDEOCONFERENCE_ENABLED = config.enabled;
		this.FEATURE_SCHULCONNEX_COURSE_SYNC_ENABLED = config.FEATURE_SCHULCONNEX_COURSE_SYNC_ENABLED;
		this.FEATURE_MEDIA_SHELF_ENABLED = config.FEATURE_MEDIA_SHELF_ENABLED;
		this.FEATURE_NEW_LAYOUT_ENABLED = config.FEATURE_NEW_LAYOUT_ENABLED;
	}
}
