import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import type { ServerConfig } from '../..';

export class ConfigResponse {
	@ApiProperty()
	FEATURE_NEW_SCHOOL_ADMINISTRATION_PAGE_AS_DEFAULT_ENABLED: boolean;

	@ApiProperty()
	MIGRATION_END_GRACE_PERIOD_MS: number;

	@ApiProperty()
	FEATURE_CTL_TOOLS_TAB_ENABLED: boolean;

	@ApiProperty()
	FEATURE_LTI_TOOLS_TAB_ENABLED: boolean;

	@ApiProperty()
	FILES_STORAGE__MAX_FILE_SIZE: number;

	@ApiProperty()
	FEATURE_SHOW_OUTDATED_USERS: boolean;

	@ApiProperty()
	FEATURE_ENABLE_LDAP_SYNC_DURING_MIGRATION: boolean;

	@ApiProperty()
	FEATURE_CTL_CONTEXT_CONFIGURATION_ENABLED: boolean;

	@ApiProperty()
	FEATURE_SHOW_NEW_CLASS_VIEW_ENABLED: boolean;

	@ApiProperty()
	FEATURE_CTL_TOOLS_COPY_ENABLED: boolean;

	@ApiProperty()
	FEATURE_SHOW_MIGRATION_WIZARD: boolean;

	@ApiPropertyOptional()
	MIGRATION_WIZARD_DOCUMENTATION_LINK?: string;

	@ApiProperty()
	FEATURE_TLDRAW_ENABLED: boolean;

	@ApiProperty()
	TLDRAW__ASSETS_ENABLED: boolean;

	@ApiProperty()
	TLDRAW__ASSETS_MAX_SIZE: number;

	@ApiProperty()
	TLDRAW__ASSETS_ALLOWED_EXTENSIONS_LIST: string;

	constructor(config: ServerConfig) {
		this.FEATURE_NEW_SCHOOL_ADMINISTRATION_PAGE_AS_DEFAULT_ENABLED =
			config.FEATURE_NEW_SCHOOL_ADMINISTRATION_PAGE_AS_DEFAULT_ENABLED;
		this.MIGRATION_END_GRACE_PERIOD_MS = config.MIGRATION_END_GRACE_PERIOD_MS;
		this.FEATURE_CTL_TOOLS_TAB_ENABLED = config.FEATURE_CTL_TOOLS_TAB_ENABLED;
		this.FEATURE_LTI_TOOLS_TAB_ENABLED = config.FEATURE_LTI_TOOLS_TAB_ENABLED;
		this.FILES_STORAGE__MAX_FILE_SIZE = config.FILES_STORAGE__MAX_FILE_SIZE;
		this.FEATURE_SHOW_OUTDATED_USERS = config.FEATURE_SHOW_OUTDATED_USERS;
		this.FEATURE_ENABLE_LDAP_SYNC_DURING_MIGRATION = config.FEATURE_ENABLE_LDAP_SYNC_DURING_MIGRATION;
		this.FEATURE_CTL_CONTEXT_CONFIGURATION_ENABLED = config.FEATURE_CTL_CONTEXT_CONFIGURATION_ENABLED;
		this.FEATURE_SHOW_NEW_CLASS_VIEW_ENABLED = config.FEATURE_SHOW_NEW_CLASS_VIEW_ENABLED;
		this.FEATURE_CTL_TOOLS_COPY_ENABLED = config.FEATURE_CTL_TOOLS_COPY_ENABLED;
		this.FEATURE_SHOW_MIGRATION_WIZARD = config.FEATURE_SHOW_MIGRATION_WIZARD;
		this.MIGRATION_WIZARD_DOCUMENTATION_LINK = config.MIGRATION_WIZARD_DOCUMENTATION_LINK;
		this.FEATURE_TLDRAW_ENABLED = config.FEATURE_TLDRAW_ENABLED;
		this.TLDRAW__ASSETS_ENABLED = config.TLDRAW__ASSETS_ENABLED;
		this.TLDRAW__ASSETS_MAX_SIZE = config.TLDRAW__ASSETS_MAX_SIZE;
		this.TLDRAW__ASSETS_ALLOWED_EXTENSIONS_LIST = config.TLDRAW__ASSETS_ALLOWED_EXTENSIONS_LIST;
	}
}
