export interface UserImportConfig {
	FEATURE_USER_MIGRATION_ENABLED: boolean;
	FEATURE_USER_MIGRATION_SYSTEM_ID: string;
	FEATURE_MIGRATION_WIZARD_WITH_USER_LOGIN_MIGRATION: boolean;
	IMPORTUSER_SAVE_ALL_MATCHES_REQUEST_TIMEOUT_MS: number;
}
