DEPLOYMENT_ENV: "prod"
SC_THEME: brb
SC_TITLE: Schul-Cloud Brandenburg
SC_SHORT_TITLE: Schul-Cloud Brandenburg
SC_PRODUCTNAME: Schul-Cloud Brandenburg
SC_NAV_TITLE: Schul-Cloud Brandenburg
#DOCUMENT_BASE_DIR:
SMTP: ""
SHOW_VERSION: 1
TEACHER_VISIBILITY_FOR_EXTERNAL_TEAM_INVITATION: opt-in
STUDENT_TEAM_CREATION: opt-out
SC_FEDERALSTATE:
ROCKETCHAT_SERVICE_ENABLED: "false"
FEATURE_CONTACT_FORM_ATTACHMENTS_ENABLED: "true"
FEATURE_ENTERTHECLOUD: "false"
FEATURE_EXTENSIONS_ENABLED: "false"
FEATURE_INSIGHTS_ENABLED: "false"
FEATURE_MATRIX_MESSENGER_ENABLED: "false"
FEATURE_MINT_PAGES_ENABLED: "false"
FEATURE_MULTIPLE_S3_PROVIDERS_ENABLED: "true"
FEATURE_NEXBOARD_ENABLED: "false"
FEATURE_TEAMS_ENABLED: "true"
FEATURE_VIDEOCONFERENCE_ENABLED: "false"
FEATURE_RABBITMQ_ENABLED: "true"
FEATURE_TSP_AUTO_CONSENT_ENABLED: "false"
FEATURE_LOG_REQUEST: "false"
SENTRY_SAMPLE_RATE: 0
ADMIN_TABLES_DISPLAY_CONSENT_COLUMN: true
AWS_ENDPOINT_URL: https://s3.hidrive.strato.com
ENABLE_FILE_SECURITY_CHECK: "true"
FILE_SECURITY_CHECK_SERVICE_URI: http://antivirus-webserver-svc:8080/scan/file
# Zusätzlich freigegebene routen
ROUTE_ACCOUNTS: true
ROUTE_CLASSES: true
ROUTE_USERS: true
## SERVER
AWS_REGION: eu-central-1
STORAGE_SIGNED_URL_EXPIRE: 600
# The date and time, when the rocket chat shall be replaced by the matrix messenger.
# ROCKET_CHAT_DEPRECATION_DATE: "2020-12-01T20:20:00+00:00"
PORT_SERVER: 3030
JWT_WHITELIST_ACCEPT_ALL: "false"
JWT_TIMEOUT_SECONDS: 7200
CONSENT_WITHOUT_PARENTS_MIN_AGE_YEARS: 18
# TSP
FEATURE_TSP_ENABLED: false
# EDU-SHARING brabu
# FEATURE_LERNSTORE_ENABLED: Completely enables or disables the ES_..., LERNSTORE_... variables.
FEATURE_LERNSTORE_ENABLED: "true"
# LERNSTORE_MODE: Valid values for LERNSTORE_MODE are: LEGACY, EDUSHARING and DISABLED
LERNSTORE_MODE: EDUSHARING
FEATURE_ES_COLLECTIONS_ENABLED: "true"
FEATURE_ES_SEARCHABLE_ENABLED: "true"
ES_DOMAIN: https://mv-repo.schul-cloud.org
# LERNSTORE_ MERLIN
FEATURE_ES_MERLIN_ENABLED: "true"
ES_MERLIN_AUTH_URL: http://merlin.nibis.de/auth.php
# EDITOR / EDTRIO
EDTR_SOURCE: https://edtrio.brandenburg.schul-cloud.org
GLOBAL_ANNOUNCEMENT: ""
# produktive Instanz
PROD_INSTANCE: true
