security:
  - jwtBearer: []
info:
  title: Schul-Cloud Password Recovery Service API
  description:
    This is the API specification for the Schul-Cloud Password Recovery service.
    
  contact:
    name: support
    email: info@hpi-schul-cloud.de
  license:
    name: GPL-3.0
    url: 'https://github.com/hpi-schul-cloud/schulcloud-server/blob/master/LICENSE'
  version: 1.0.0
components:
  securitySchemes:
    jwtBearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    passwordRecovery:
      description: TODO
    reset:
      description: TODO

paths:
  '/passwordRecovery/{id}':
    get:
      parameters:
        - in: path
          name: id
          description: ID of passwordRecovery to return
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/passwordRecovery'
        '401':
          description: not authenticated
        '404':
          description: not found
        '500':
          description: general error
      description: Retrieves a single resource with the given id from the service.
      summary: ''
      tags:
        - passwordRecovery
      security: []
  /passwordRecovery:
    post:
      parameters: []
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/passwordRecovery'
        '401':
          description: not authenticated
        '500':
          description: general error
      description: Creates a new resource with data.
      summary: ''
      tags:
        - passwordRecovery
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/passwordRecovery'
  /passwordRecovery/reset:
    post:
      parameters: []
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reset'
        '401':
          description: not authenticated
        '500':
          description: general error
      description: Creates a new resource with data.
      summary: ''
      tags:
        - passwordRecovery
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/reset'
  
openapi: 3.0.2
tags:
  - name: passwordRecovery
    description: A passwordRecovery service.
