/* tslint:disable */
/* eslint-disable */
/**
 * HPI Schul-Cloud Server API
 * This is v3 of HPI Schul-Cloud Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { TaskResponse } from './task-response';

/**
 * 
 * @export
 * @interface TaskListResponse
 */
export interface TaskListResponse {
    /**
     * 
     * @type {Array<TaskResponse>}
     * @memberof TaskListResponse
     */
    'data': Array<TaskResponse>;
    /**
     * 
     * @type {number}
     * @memberof TaskListResponse
     */
    'total': number;
    /**
     * 
     * @type {number}
     * @memberof TaskListResponse
     */
    'skip': number;
    /**
     * 
     * @type {number}
     * @memberof TaskListResponse
     */
    'limit': number;
}

