/* tslint:disable */
/* eslint-disable */
/**
 * HPI Schul-Cloud Server API
 * This is v3 of HPI Schul-Cloud Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { TaskStatusResponse } from './task-status-response';

/**
 * 
 * @export
 * @interface TaskResponse
 */
export interface TaskResponse {
    /**
     * 
     * @type {string}
     * @memberof TaskResponse
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof TaskResponse
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof TaskResponse
     */
    'availableDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskResponse
     */
    'duedate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskResponse
     */
    'courseName': string;
    /**
     * 
     * @type {string}
     * @memberof TaskResponse
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskResponse
     */
    'displayColor'?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskResponse
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof TaskResponse
     */
    'updatedAt': string;
    /**
     * 
     * @type {TaskStatusResponse}
     * @memberof TaskResponse
     */
    'status': TaskStatusResponse;
}

