/* tslint:disable */
/* eslint-disable */
/**
 * HPI Schul-Cloud Server API
 * This is v3 of HPI Schul-Cloud Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { UserResponse } from './user-response';

/**
 * 
 * @export
 * @interface UserListResponse
 */
export interface UserListResponse {
    /**
     * 
     * @type {Array<UserResponse>}
     * @memberof UserListResponse
     */
    'data': Array<UserResponse>;
    /**
     * 
     * @type {number}
     * @memberof UserListResponse
     */
    'total': number;
    /**
     * 
     * @type {number}
     * @memberof UserListResponse
     */
    'skip': number;
    /**
     * 
     * @type {number}
     * @memberof UserListResponse
     */
    'limit': number;
}

