export enum CommonCartridgeErrorEnum {
	VERSION_NOT_SUPPORTED = 'VERSION_NOT_SUPPORTED',
	RESOURCE_TYPE_NOT_SUPPORTED = 'RESOURCE_TYPE_NOT_SUPPORTED',
	ELEMENT_TYPE_NOT_SUPPORTED = 'ELEMENT_TYPE_NOT_SUPPORTED',
	INTENDED_USE_NOT_SUPPORTED = 'INTENDED_USE_NOT_SUPPORTED',
	MISSING_METADATA = 'MISSING_METADATA',
}
