name: Run Cypress tests

on:
  pull_request:
    branches:
      - main
    types: [labeled]

jobs:
  cypress-tests:
    if: contains(github.event.pull_request.labels.*.name, 'run-tests')

    runs-on: ubuntu-latest

    steps:
      uses: hpi-schul-cloud/e2e-system-tests/.github/workflows/remote-trigger.yml@main
      with:
        ref: ${{ github.event.pull_request.head.ref }}
      secrets:
        service-account-token: ${{ secrets.CYPRESS_ONEPWD_SERVICE_ACCOUNT_TOKEN }}