---
name: Build and push Docker Image on Tag

on:
  push:
    tags:
      - '[0-9]*'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Docker meta Service Name for docker hub
        id: docker_meta_img_hub
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          images: docker.io/schulcloud/schulcloud-server, quay.io/schulcloudverbund/schulcloud-server
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Log into docker registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Log into quay registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build and push ${{ github.repository }}
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          pull: true
          tags: ${{ steps.docker_meta_img_hub.outputs.tags }}
          labels: ${{ steps.docker_meta_img_hub.outputs.labels }}

  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: generate sbom via dependency-graph
        run: gh api repos/${{ github.repository }}/dependency-graph/sbom > dependencies.sbom.json
        env:
          GH_TOKEN: ${{ github.token }}
      - name: create release
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # v2.6.1
        with:
          files: dependencies.sbom.json
