export interface IIdentityManagementConfig {
	FEATURE_IMSCC_COURSE_EXPORT_ENABLED: boolean;
	FEATURE_IDENTITY_MANAGEMENT_STORE_ENABLED: boolean;
	FEATURE_IDENTITY_MANAGEMENT_LOGIN_ENABLED: boolean;
}
