export interface IIdentityManagementConfig {
	FEATURE_IDENTITY_MANAGEMENT_ENABLED: boolean;
	FEATURE_IDENTITY_MANAGEMENT_STORE_ENABLED: boolean;
	FEATURE_IDENTITY_MANAGEMENT_LOGIN_ENABLED: boolean;
}
